// Code generated by counterfeiter. DO NOT EDIT.
package apifakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/binder/api"
	"github.com/simeonkorchev/binder/internal/binder/model"
)

type FakeService struct {
	AddSlotStub        func(context.Context, uuid.UUID, uuid.UUID, model.AddSlotInput) (model.Slot, error)
	addSlotMutex       sync.RWMutex
	addSlotArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 model.AddSlotInput
	}
	addSlotReturns struct {
		result1 model.Slot
		result2 error
	}
	addSlotReturnsOnCall map[int]struct {
		result1 model.Slot
		result2 error
	}
	CreateBinderStub        func(context.Context, uuid.UUID, string) (model.Binder, error)
	createBinderMutex       sync.RWMutex
	createBinderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	createBinderReturns struct {
		result1 model.Binder
		result2 error
	}
	createBinderReturnsOnCall map[int]struct {
		result1 model.Binder
		result2 error
	}
	GetPageStub        func(context.Context, uuid.UUID, uuid.UUID, int) (model.Page, error)
	getPageMutex       sync.RWMutex
	getPageArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}
	getPageReturns struct {
		result1 model.Page
		result2 error
	}
	getPageReturnsOnCall map[int]struct {
		result1 model.Page
		result2 error
	}
	ListBindersStub        func(context.Context, uuid.UUID) ([]model.Binder, error)
	listBindersMutex       sync.RWMutex
	listBindersArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	listBindersReturns struct {
		result1 []model.Binder
		result2 error
	}
	listBindersReturnsOnCall map[int]struct {
		result1 []model.Binder
		result2 error
	}
	MoveSlotStub        func(context.Context, uuid.UUID, uuid.UUID, model.MoveSlotInput) error
	moveSlotMutex       sync.RWMutex
	moveSlotArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 model.MoveSlotInput
	}
	moveSlotReturns struct {
		result1 error
	}
	moveSlotReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveSlotStub        func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error
	removeSlotMutex       sync.RWMutex
	removeSlotArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}
	removeSlotReturns struct {
		result1 error
	}
	removeSlotReturnsOnCall map[int]struct {
		result1 error
	}
	RenameBinderStub        func(context.Context, uuid.UUID, uuid.UUID, string) (model.Binder, error)
	renameBinderMutex       sync.RWMutex
	renameBinderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 string
	}
	renameBinderReturns struct {
		result1 model.Binder
		result2 error
	}
	renameBinderReturnsOnCall map[int]struct {
		result1 model.Binder
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) AddSlot(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 model.AddSlotInput) (model.Slot, error) {
	fake.addSlotMutex.Lock()
	ret, specificReturn := fake.addSlotReturnsOnCall[len(fake.addSlotArgsForCall)]
	fake.addSlotArgsForCall = append(fake.addSlotArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 model.AddSlotInput
	}{arg1, arg2, arg3, arg4})
	stub := fake.AddSlotStub
	fakeReturns := fake.addSlotReturns
	fake.recordInvocation("AddSlot", []interface{}{arg1, arg2, arg3, arg4})
	fake.addSlotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) AddSlotCallCount() int {
	fake.addSlotMutex.RLock()
	defer fake.addSlotMutex.RUnlock()
	return len(fake.addSlotArgsForCall)
}

func (fake *FakeService) AddSlotCalls(stub func(context.Context, uuid.UUID, uuid.UUID, model.AddSlotInput) (model.Slot, error)) {
	fake.addSlotMutex.Lock()
	defer fake.addSlotMutex.Unlock()
	fake.AddSlotStub = stub
}

func (fake *FakeService) AddSlotArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, model.AddSlotInput) {
	fake.addSlotMutex.RLock()
	defer fake.addSlotMutex.RUnlock()
	argsForCall := fake.addSlotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) AddSlotReturns(result1 model.Slot, result2 error) {
	fake.addSlotMutex.Lock()
	defer fake.addSlotMutex.Unlock()
	fake.AddSlotStub = nil
	fake.addSlotReturns = struct {
		result1 model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeService) AddSlotReturnsOnCall(i int, result1 model.Slot, result2 error) {
	fake.addSlotMutex.Lock()
	defer fake.addSlotMutex.Unlock()
	fake.AddSlotStub = nil
	if fake.addSlotReturnsOnCall == nil {
		fake.addSlotReturnsOnCall = make(map[int]struct {
			result1 model.Slot
			result2 error
		})
	}
	fake.addSlotReturnsOnCall[i] = struct {
		result1 model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateBinder(arg1 context.Context, arg2 uuid.UUID, arg3 string) (model.Binder, error) {
	fake.createBinderMutex.Lock()
	ret, specificReturn := fake.createBinderReturnsOnCall[len(fake.createBinderArgsForCall)]
	fake.createBinderArgsForCall = append(fake.createBinderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.CreateBinderStub
	fakeReturns := fake.createBinderReturns
	fake.recordInvocation("CreateBinder", []interface{}{arg1, arg2, arg3})
	fake.createBinderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreateBinderCallCount() int {
	fake.createBinderMutex.RLock()
	defer fake.createBinderMutex.RUnlock()
	return len(fake.createBinderArgsForCall)
}

func (fake *FakeService) CreateBinderCalls(stub func(context.Context, uuid.UUID, string) (model.Binder, error)) {
	fake.createBinderMutex.Lock()
	defer fake.createBinderMutex.Unlock()
	fake.CreateBinderStub = stub
}

func (fake *FakeService) CreateBinderArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.createBinderMutex.RLock()
	defer fake.createBinderMutex.RUnlock()
	argsForCall := fake.createBinderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) CreateBinderReturns(result1 model.Binder, result2 error) {
	fake.createBinderMutex.Lock()
	defer fake.createBinderMutex.Unlock()
	fake.CreateBinderStub = nil
	fake.createBinderReturns = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateBinderReturnsOnCall(i int, result1 model.Binder, result2 error) {
	fake.createBinderMutex.Lock()
	defer fake.createBinderMutex.Unlock()
	fake.CreateBinderStub = nil
	if fake.createBinderReturnsOnCall == nil {
		fake.createBinderReturnsOnCall = make(map[int]struct {
			result1 model.Binder
			result2 error
		})
	}
	fake.createBinderReturnsOnCall[i] = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetPage(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int) (model.Page, error) {
	fake.getPageMutex.Lock()
	ret, specificReturn := fake.getPageReturnsOnCall[len(fake.getPageArgsForCall)]
	fake.getPageArgsForCall = append(fake.getPageArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetPageStub
	fakeReturns := fake.getPageReturns
	fake.recordInvocation("GetPage", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetPageCallCount() int {
	fake.getPageMutex.RLock()
	defer fake.getPageMutex.RUnlock()
	return len(fake.getPageArgsForCall)
}

func (fake *FakeService) GetPageCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int) (model.Page, error)) {
	fake.getPageMutex.Lock()
	defer fake.getPageMutex.Unlock()
	fake.GetPageStub = stub
}

func (fake *FakeService) GetPageArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int) {
	fake.getPageMutex.RLock()
	defer fake.getPageMutex.RUnlock()
	argsForCall := fake.getPageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) GetPageReturns(result1 model.Page, result2 error) {
	fake.getPageMutex.Lock()
	defer fake.getPageMutex.Unlock()
	fake.GetPageStub = nil
	fake.getPageReturns = struct {
		result1 model.Page
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetPageReturnsOnCall(i int, result1 model.Page, result2 error) {
	fake.getPageMutex.Lock()
	defer fake.getPageMutex.Unlock()
	fake.GetPageStub = nil
	if fake.getPageReturnsOnCall == nil {
		fake.getPageReturnsOnCall = make(map[int]struct {
			result1 model.Page
			result2 error
		})
	}
	fake.getPageReturnsOnCall[i] = struct {
		result1 model.Page
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListBinders(arg1 context.Context, arg2 uuid.UUID) ([]model.Binder, error) {
	fake.listBindersMutex.Lock()
	ret, specificReturn := fake.listBindersReturnsOnCall[len(fake.listBindersArgsForCall)]
	fake.listBindersArgsForCall = append(fake.listBindersArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.ListBindersStub
	fakeReturns := fake.listBindersReturns
	fake.recordInvocation("ListBinders", []interface{}{arg1, arg2})
	fake.listBindersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListBindersCallCount() int {
	fake.listBindersMutex.RLock()
	defer fake.listBindersMutex.RUnlock()
	return len(fake.listBindersArgsForCall)
}

func (fake *FakeService) ListBindersCalls(stub func(context.Context, uuid.UUID) ([]model.Binder, error)) {
	fake.listBindersMutex.Lock()
	defer fake.listBindersMutex.Unlock()
	fake.ListBindersStub = stub
}

func (fake *FakeService) ListBindersArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.listBindersMutex.RLock()
	defer fake.listBindersMutex.RUnlock()
	argsForCall := fake.listBindersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ListBindersReturns(result1 []model.Binder, result2 error) {
	fake.listBindersMutex.Lock()
	defer fake.listBindersMutex.Unlock()
	fake.ListBindersStub = nil
	fake.listBindersReturns = struct {
		result1 []model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListBindersReturnsOnCall(i int, result1 []model.Binder, result2 error) {
	fake.listBindersMutex.Lock()
	defer fake.listBindersMutex.Unlock()
	fake.ListBindersStub = nil
	if fake.listBindersReturnsOnCall == nil {
		fake.listBindersReturnsOnCall = make(map[int]struct {
			result1 []model.Binder
			result2 error
		})
	}
	fake.listBindersReturnsOnCall[i] = struct {
		result1 []model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeService) MoveSlot(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 model.MoveSlotInput) error {
	fake.moveSlotMutex.Lock()
	ret, specificReturn := fake.moveSlotReturnsOnCall[len(fake.moveSlotArgsForCall)]
	fake.moveSlotArgsForCall = append(fake.moveSlotArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 model.MoveSlotInput
	}{arg1, arg2, arg3, arg4})
	stub := fake.MoveSlotStub
	fakeReturns := fake.moveSlotReturns
	fake.recordInvocation("MoveSlot", []interface{}{arg1, arg2, arg3, arg4})
	fake.moveSlotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) MoveSlotCallCount() int {
	fake.moveSlotMutex.RLock()
	defer fake.moveSlotMutex.RUnlock()
	return len(fake.moveSlotArgsForCall)
}

func (fake *FakeService) MoveSlotCalls(stub func(context.Context, uuid.UUID, uuid.UUID, model.MoveSlotInput) error) {
	fake.moveSlotMutex.Lock()
	defer fake.moveSlotMutex.Unlock()
	fake.MoveSlotStub = stub
}

func (fake *FakeService) MoveSlotArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, model.MoveSlotInput) {
	fake.moveSlotMutex.RLock()
	defer fake.moveSlotMutex.RUnlock()
	argsForCall := fake.moveSlotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) MoveSlotReturns(result1 error) {
	fake.moveSlotMutex.Lock()
	defer fake.moveSlotMutex.Unlock()
	fake.MoveSlotStub = nil
	fake.moveSlotReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) MoveSlotReturnsOnCall(i int, result1 error) {
	fake.moveSlotMutex.Lock()
	defer fake.moveSlotMutex.Unlock()
	fake.MoveSlotStub = nil
	if fake.moveSlotReturnsOnCall == nil {
		fake.moveSlotReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveSlotReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) RemoveSlot(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 uuid.UUID) error {
	fake.removeSlotMutex.Lock()
	ret, specificReturn := fake.removeSlotReturnsOnCall[len(fake.removeSlotArgsForCall)]
	fake.removeSlotArgsForCall = append(fake.removeSlotArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}{arg1, arg2, arg3, arg4})
	stub := fake.RemoveSlotStub
	fakeReturns := fake.removeSlotReturns
	fake.recordInvocation("RemoveSlot", []interface{}{arg1, arg2, arg3, arg4})
	fake.removeSlotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) RemoveSlotCallCount() int {
	fake.removeSlotMutex.RLock()
	defer fake.removeSlotMutex.RUnlock()
	return len(fake.removeSlotArgsForCall)
}

func (fake *FakeService) RemoveSlotCalls(stub func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) {
	fake.removeSlotMutex.Lock()
	defer fake.removeSlotMutex.Unlock()
	fake.RemoveSlotStub = stub
}

func (fake *FakeService) RemoveSlotArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, uuid.UUID) {
	fake.removeSlotMutex.RLock()
	defer fake.removeSlotMutex.RUnlock()
	argsForCall := fake.removeSlotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) RemoveSlotReturns(result1 error) {
	fake.removeSlotMutex.Lock()
	defer fake.removeSlotMutex.Unlock()
	fake.RemoveSlotStub = nil
	fake.removeSlotReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) RemoveSlotReturnsOnCall(i int, result1 error) {
	fake.removeSlotMutex.Lock()
	defer fake.removeSlotMutex.Unlock()
	fake.RemoveSlotStub = nil
	if fake.removeSlotReturnsOnCall == nil {
		fake.removeSlotReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeSlotReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) RenameBinder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 string) (model.Binder, error) {
	fake.renameBinderMutex.Lock()
	ret, specificReturn := fake.renameBinderReturnsOnCall[len(fake.renameBinderArgsForCall)]
	fake.renameBinderArgsForCall = append(fake.renameBinderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.RenameBinderStub
	fakeReturns := fake.renameBinderReturns
	fake.recordInvocation("RenameBinder", []interface{}{arg1, arg2, arg3, arg4})
	fake.renameBinderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) RenameBinderCallCount() int {
	fake.renameBinderMutex.RLock()
	defer fake.renameBinderMutex.RUnlock()
	return len(fake.renameBinderArgsForCall)
}

func (fake *FakeService) RenameBinderCalls(stub func(context.Context, uuid.UUID, uuid.UUID, string) (model.Binder, error)) {
	fake.renameBinderMutex.Lock()
	defer fake.renameBinderMutex.Unlock()
	fake.RenameBinderStub = stub
}

func (fake *FakeService) RenameBinderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, string) {
	fake.renameBinderMutex.RLock()
	defer fake.renameBinderMutex.RUnlock()
	argsForCall := fake.renameBinderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) RenameBinderReturns(result1 model.Binder, result2 error) {
	fake.renameBinderMutex.Lock()
	defer fake.renameBinderMutex.Unlock()
	fake.RenameBinderStub = nil
	fake.renameBinderReturns = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeService) RenameBinderReturnsOnCall(i int, result1 model.Binder, result2 error) {
	fake.renameBinderMutex.Lock()
	defer fake.renameBinderMutex.Unlock()
	fake.RenameBinderStub = nil
	if fake.renameBinderReturnsOnCall == nil {
		fake.renameBinderReturnsOnCall = make(map[int]struct {
			result1 model.Binder
			result2 error
		})
	}
	fake.renameBinderReturnsOnCall[i] = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.Service = new(FakeService)
