// Code generated by counterfeiter. DO NOT EDIT.
package apifakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/listing/api"
	"github.com/simeonkorchev/binder/internal/listing/model"
)

type FakeService struct {
	BrowseListingsStub        func(context.Context, model.ListingSearch) ([]model.ListedCard, error)
	browseListingsMutex       sync.RWMutex
	browseListingsArgsForCall []struct {
		arg1 context.Context
		arg2 model.ListingSearch
	}
	browseListingsReturns struct {
		result1 []model.ListedCard
		result2 error
	}
	browseListingsReturnsOnCall map[int]struct {
		result1 []model.ListedCard
		result2 error
	}
	CreateListingStub        func(context.Context, uuid.UUID, uuid.UUID) (model.Listing, error)
	createListingMutex       sync.RWMutex
	createListingArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	createListingReturns struct {
		result1 model.Listing
		result2 error
	}
	createListingReturnsOnCall map[int]struct {
		result1 model.Listing
		result2 error
	}
	DeleteListingStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteListingMutex       sync.RWMutex
	deleteListingArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteListingReturns struct {
		result1 error
	}
	deleteListingReturnsOnCall map[int]struct {
		result1 error
	}
	SellerContactStub        func(context.Context, uuid.UUID) (model.SellerContact, error)
	sellerContactMutex       sync.RWMutex
	sellerContactArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	sellerContactReturns struct {
		result1 model.SellerContact
		result2 error
	}
	sellerContactReturnsOnCall map[int]struct {
		result1 model.SellerContact
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) BrowseListings(arg1 context.Context, arg2 model.ListingSearch) ([]model.ListedCard, error) {
	fake.browseListingsMutex.Lock()
	ret, specificReturn := fake.browseListingsReturnsOnCall[len(fake.browseListingsArgsForCall)]
	fake.browseListingsArgsForCall = append(fake.browseListingsArgsForCall, struct {
		arg1 context.Context
		arg2 model.ListingSearch
	}{arg1, arg2})
	stub := fake.BrowseListingsStub
	fakeReturns := fake.browseListingsReturns
	fake.recordInvocation("BrowseListings", []interface{}{arg1, arg2})
	fake.browseListingsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) BrowseListingsCallCount() int {
	fake.browseListingsMutex.RLock()
	defer fake.browseListingsMutex.RUnlock()
	return len(fake.browseListingsArgsForCall)
}

func (fake *FakeService) BrowseListingsCalls(stub func(context.Context, model.ListingSearch) ([]model.ListedCard, error)) {
	fake.browseListingsMutex.Lock()
	defer fake.browseListingsMutex.Unlock()
	fake.BrowseListingsStub = stub
}

func (fake *FakeService) BrowseListingsArgsForCall(i int) (context.Context, model.ListingSearch) {
	fake.browseListingsMutex.RLock()
	defer fake.browseListingsMutex.RUnlock()
	argsForCall := fake.browseListingsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) BrowseListingsReturns(result1 []model.ListedCard, result2 error) {
	fake.browseListingsMutex.Lock()
	defer fake.browseListingsMutex.Unlock()
	fake.BrowseListingsStub = nil
	fake.browseListingsReturns = struct {
		result1 []model.ListedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeService) BrowseListingsReturnsOnCall(i int, result1 []model.ListedCard, result2 error) {
	fake.browseListingsMutex.Lock()
	defer fake.browseListingsMutex.Unlock()
	fake.BrowseListingsStub = nil
	if fake.browseListingsReturnsOnCall == nil {
		fake.browseListingsReturnsOnCall = make(map[int]struct {
			result1 []model.ListedCard
			result2 error
		})
	}
	fake.browseListingsReturnsOnCall[i] = struct {
		result1 []model.ListedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateListing(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (model.Listing, error) {
	fake.createListingMutex.Lock()
	ret, specificReturn := fake.createListingReturnsOnCall[len(fake.createListingArgsForCall)]
	fake.createListingArgsForCall = append(fake.createListingArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.CreateListingStub
	fakeReturns := fake.createListingReturns
	fake.recordInvocation("CreateListing", []interface{}{arg1, arg2, arg3})
	fake.createListingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreateListingCallCount() int {
	fake.createListingMutex.RLock()
	defer fake.createListingMutex.RUnlock()
	return len(fake.createListingArgsForCall)
}

func (fake *FakeService) CreateListingCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (model.Listing, error)) {
	fake.createListingMutex.Lock()
	defer fake.createListingMutex.Unlock()
	fake.CreateListingStub = stub
}

func (fake *FakeService) CreateListingArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.createListingMutex.RLock()
	defer fake.createListingMutex.RUnlock()
	argsForCall := fake.createListingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) CreateListingReturns(result1 model.Listing, result2 error) {
	fake.createListingMutex.Lock()
	defer fake.createListingMutex.Unlock()
	fake.CreateListingStub = nil
	fake.createListingReturns = struct {
		result1 model.Listing
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateListingReturnsOnCall(i int, result1 model.Listing, result2 error) {
	fake.createListingMutex.Lock()
	defer fake.createListingMutex.Unlock()
	fake.CreateListingStub = nil
	if fake.createListingReturnsOnCall == nil {
		fake.createListingReturnsOnCall = make(map[int]struct {
			result1 model.Listing
			result2 error
		})
	}
	fake.createListingReturnsOnCall[i] = struct {
		result1 model.Listing
		result2 error
	}{result1, result2}
}

func (fake *FakeService) DeleteListing(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteListingMutex.Lock()
	ret, specificReturn := fake.deleteListingReturnsOnCall[len(fake.deleteListingArgsForCall)]
	fake.deleteListingArgsForCall = append(fake.deleteListingArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteListingStub
	fakeReturns := fake.deleteListingReturns
	fake.recordInvocation("DeleteListing", []interface{}{arg1, arg2, arg3})
	fake.deleteListingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) DeleteListingCallCount() int {
	fake.deleteListingMutex.RLock()
	defer fake.deleteListingMutex.RUnlock()
	return len(fake.deleteListingArgsForCall)
}

func (fake *FakeService) DeleteListingCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteListingMutex.Lock()
	defer fake.deleteListingMutex.Unlock()
	fake.DeleteListingStub = stub
}

func (fake *FakeService) DeleteListingArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteListingMutex.RLock()
	defer fake.deleteListingMutex.RUnlock()
	argsForCall := fake.deleteListingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) DeleteListingReturns(result1 error) {
	fake.deleteListingMutex.Lock()
	defer fake.deleteListingMutex.Unlock()
	fake.DeleteListingStub = nil
	fake.deleteListingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) DeleteListingReturnsOnCall(i int, result1 error) {
	fake.deleteListingMutex.Lock()
	defer fake.deleteListingMutex.Unlock()
	fake.DeleteListingStub = nil
	if fake.deleteListingReturnsOnCall == nil {
		fake.deleteListingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteListingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) SellerContact(arg1 context.Context, arg2 uuid.UUID) (model.SellerContact, error) {
	fake.sellerContactMutex.Lock()
	ret, specificReturn := fake.sellerContactReturnsOnCall[len(fake.sellerContactArgsForCall)]
	fake.sellerContactArgsForCall = append(fake.sellerContactArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.SellerContactStub
	fakeReturns := fake.sellerContactReturns
	fake.recordInvocation("SellerContact", []interface{}{arg1, arg2})
	fake.sellerContactMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SellerContactCallCount() int {
	fake.sellerContactMutex.RLock()
	defer fake.sellerContactMutex.RUnlock()
	return len(fake.sellerContactArgsForCall)
}

func (fake *FakeService) SellerContactCalls(stub func(context.Context, uuid.UUID) (model.SellerContact, error)) {
	fake.sellerContactMutex.Lock()
	defer fake.sellerContactMutex.Unlock()
	fake.SellerContactStub = stub
}

func (fake *FakeService) SellerContactArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.sellerContactMutex.RLock()
	defer fake.sellerContactMutex.RUnlock()
	argsForCall := fake.sellerContactArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) SellerContactReturns(result1 model.SellerContact, result2 error) {
	fake.sellerContactMutex.Lock()
	defer fake.sellerContactMutex.Unlock()
	fake.SellerContactStub = nil
	fake.sellerContactReturns = struct {
		result1 model.SellerContact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SellerContactReturnsOnCall(i int, result1 model.SellerContact, result2 error) {
	fake.sellerContactMutex.Lock()
	defer fake.sellerContactMutex.Unlock()
	fake.SellerContactStub = nil
	if fake.sellerContactReturnsOnCall == nil {
		fake.sellerContactReturnsOnCall = make(map[int]struct {
			result1 model.SellerContact
			result2 error
		})
	}
	fake.sellerContactReturnsOnCall[i] = struct {
		result1 model.SellerContact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.Service = new(FakeService)
