// Code generated by counterfeiter. DO NOT EDIT.
package apifakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/user/api"
	"github.com/simeonkorchev/binder/internal/user/model"
)

type FakeService struct {
	GetUserStub        func(context.Context, uuid.UUID) (model.User, error)
	getUserMutex       sync.RWMutex
	getUserArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	getUserReturns struct {
		result1 model.User
		result2 error
	}
	getUserReturnsOnCall map[int]struct {
		result1 model.User
		result2 error
	}
	SetContactStub        func(context.Context, uuid.UUID, model.Contact) (model.User, error)
	setContactMutex       sync.RWMutex
	setContactArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 model.Contact
	}
	setContactReturns struct {
		result1 model.User
		result2 error
	}
	setContactReturnsOnCall map[int]struct {
		result1 model.User
		result2 error
	}
	SignInStub        func(context.Context, model.SignIn) (model.Session, error)
	signInMutex       sync.RWMutex
	signInArgsForCall []struct {
		arg1 context.Context
		arg2 model.SignIn
	}
	signInReturns struct {
		result1 model.Session
		result2 error
	}
	signInReturnsOnCall map[int]struct {
		result1 model.Session
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) GetUser(arg1 context.Context, arg2 uuid.UUID) (model.User, error) {
	fake.getUserMutex.Lock()
	ret, specificReturn := fake.getUserReturnsOnCall[len(fake.getUserArgsForCall)]
	fake.getUserArgsForCall = append(fake.getUserArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.GetUserStub
	fakeReturns := fake.getUserReturns
	fake.recordInvocation("GetUser", []interface{}{arg1, arg2})
	fake.getUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetUserCallCount() int {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	return len(fake.getUserArgsForCall)
}

func (fake *FakeService) GetUserCalls(stub func(context.Context, uuid.UUID) (model.User, error)) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = stub
}

func (fake *FakeService) GetUserArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	argsForCall := fake.getUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetUserReturns(result1 model.User, result2 error) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = nil
	fake.getUserReturns = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetUserReturnsOnCall(i int, result1 model.User, result2 error) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = nil
	if fake.getUserReturnsOnCall == nil {
		fake.getUserReturnsOnCall = make(map[int]struct {
			result1 model.User
			result2 error
		})
	}
	fake.getUserReturnsOnCall[i] = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SetContact(arg1 context.Context, arg2 uuid.UUID, arg3 model.Contact) (model.User, error) {
	fake.setContactMutex.Lock()
	ret, specificReturn := fake.setContactReturnsOnCall[len(fake.setContactArgsForCall)]
	fake.setContactArgsForCall = append(fake.setContactArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 model.Contact
	}{arg1, arg2, arg3})
	stub := fake.SetContactStub
	fakeReturns := fake.setContactReturns
	fake.recordInvocation("SetContact", []interface{}{arg1, arg2, arg3})
	fake.setContactMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SetContactCallCount() int {
	fake.setContactMutex.RLock()
	defer fake.setContactMutex.RUnlock()
	return len(fake.setContactArgsForCall)
}

func (fake *FakeService) SetContactCalls(stub func(context.Context, uuid.UUID, model.Contact) (model.User, error)) {
	fake.setContactMutex.Lock()
	defer fake.setContactMutex.Unlock()
	fake.SetContactStub = stub
}

func (fake *FakeService) SetContactArgsForCall(i int) (context.Context, uuid.UUID, model.Contact) {
	fake.setContactMutex.RLock()
	defer fake.setContactMutex.RUnlock()
	argsForCall := fake.setContactArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) SetContactReturns(result1 model.User, result2 error) {
	fake.setContactMutex.Lock()
	defer fake.setContactMutex.Unlock()
	fake.SetContactStub = nil
	fake.setContactReturns = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SetContactReturnsOnCall(i int, result1 model.User, result2 error) {
	fake.setContactMutex.Lock()
	defer fake.setContactMutex.Unlock()
	fake.SetContactStub = nil
	if fake.setContactReturnsOnCall == nil {
		fake.setContactReturnsOnCall = make(map[int]struct {
			result1 model.User
			result2 error
		})
	}
	fake.setContactReturnsOnCall[i] = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SignIn(arg1 context.Context, arg2 model.SignIn) (model.Session, error) {
	fake.signInMutex.Lock()
	ret, specificReturn := fake.signInReturnsOnCall[len(fake.signInArgsForCall)]
	fake.signInArgsForCall = append(fake.signInArgsForCall, struct {
		arg1 context.Context
		arg2 model.SignIn
	}{arg1, arg2})
	stub := fake.SignInStub
	fakeReturns := fake.signInReturns
	fake.recordInvocation("SignIn", []interface{}{arg1, arg2})
	fake.signInMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SignInCallCount() int {
	fake.signInMutex.RLock()
	defer fake.signInMutex.RUnlock()
	return len(fake.signInArgsForCall)
}

func (fake *FakeService) SignInCalls(stub func(context.Context, model.SignIn) (model.Session, error)) {
	fake.signInMutex.Lock()
	defer fake.signInMutex.Unlock()
	fake.SignInStub = stub
}

func (fake *FakeService) SignInArgsForCall(i int) (context.Context, model.SignIn) {
	fake.signInMutex.RLock()
	defer fake.signInMutex.RUnlock()
	argsForCall := fake.signInArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) SignInReturns(result1 model.Session, result2 error) {
	fake.signInMutex.Lock()
	defer fake.signInMutex.Unlock()
	fake.SignInStub = nil
	fake.signInReturns = struct {
		result1 model.Session
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SignInReturnsOnCall(i int, result1 model.Session, result2 error) {
	fake.signInMutex.Lock()
	defer fake.signInMutex.Unlock()
	fake.SignInStub = nil
	if fake.signInReturnsOnCall == nil {
		fake.signInReturnsOnCall = make(map[int]struct {
			result1 model.Session
			result2 error
		})
	}
	fake.signInReturnsOnCall[i] = struct {
		result1 model.Session
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.Service = new(FakeService)
