// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"sync"

	"github.com/simeonkorchev/binder/internal/card/model"
	"github.com/simeonkorchev/binder/internal/card/service"
)

type FakeStore struct {
	FindCardsByNameStub        func(context.Context, string, float64, int) ([]model.NameMatch, error)
	findCardsByNameMutex       sync.RWMutex
	findCardsByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 float64
		arg4 int
	}
	findCardsByNameReturns struct {
		result1 []model.NameMatch
		result2 error
	}
	findCardsByNameReturnsOnCall map[int]struct {
		result1 []model.NameMatch
		result2 error
	}
	FindPrintingsBySetCodeStub        func(context.Context, string) ([]model.PrintedCard, error)
	findPrintingsBySetCodeMutex       sync.RWMutex
	findPrintingsBySetCodeArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findPrintingsBySetCodeReturns struct {
		result1 []model.PrintedCard
		result2 error
	}
	findPrintingsBySetCodeReturnsOnCall map[int]struct {
		result1 []model.PrintedCard
		result2 error
	}
	FindPrintingsBySetNumberStub        func(context.Context, string) ([]model.PrintedCard, error)
	findPrintingsBySetNumberMutex       sync.RWMutex
	findPrintingsBySetNumberArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findPrintingsBySetNumberReturns struct {
		result1 []model.PrintedCard
		result2 error
	}
	findPrintingsBySetNumberReturnsOnCall map[int]struct {
		result1 []model.PrintedCard
		result2 error
	}
	FindPrintingsBySetPrefixAndNumberStub        func(context.Context, string, string) ([]model.PrintedCard, error)
	findPrintingsBySetPrefixAndNumberMutex       sync.RWMutex
	findPrintingsBySetPrefixAndNumberArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findPrintingsBySetPrefixAndNumberReturns struct {
		result1 []model.PrintedCard
		result2 error
	}
	findPrintingsBySetPrefixAndNumberReturnsOnCall map[int]struct {
		result1 []model.PrintedCard
		result2 error
	}
	SearchCardsStub        func(context.Context, model.CardSearch) ([]model.Card, error)
	searchCardsMutex       sync.RWMutex
	searchCardsArgsForCall []struct {
		arg1 context.Context
		arg2 model.CardSearch
	}
	searchCardsReturns struct {
		result1 []model.Card
		result2 error
	}
	searchCardsReturnsOnCall map[int]struct {
		result1 []model.Card
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) FindCardsByName(arg1 context.Context, arg2 string, arg3 float64, arg4 int) ([]model.NameMatch, error) {
	fake.findCardsByNameMutex.Lock()
	ret, specificReturn := fake.findCardsByNameReturnsOnCall[len(fake.findCardsByNameArgsForCall)]
	fake.findCardsByNameArgsForCall = append(fake.findCardsByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 float64
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.FindCardsByNameStub
	fakeReturns := fake.findCardsByNameReturns
	fake.recordInvocation("FindCardsByName", []interface{}{arg1, arg2, arg3, arg4})
	fake.findCardsByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) FindCardsByNameCallCount() int {
	fake.findCardsByNameMutex.RLock()
	defer fake.findCardsByNameMutex.RUnlock()
	return len(fake.findCardsByNameArgsForCall)
}

func (fake *FakeStore) FindCardsByNameCalls(stub func(context.Context, string, float64, int) ([]model.NameMatch, error)) {
	fake.findCardsByNameMutex.Lock()
	defer fake.findCardsByNameMutex.Unlock()
	fake.FindCardsByNameStub = stub
}

func (fake *FakeStore) FindCardsByNameArgsForCall(i int) (context.Context, string, float64, int) {
	fake.findCardsByNameMutex.RLock()
	defer fake.findCardsByNameMutex.RUnlock()
	argsForCall := fake.findCardsByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeStore) FindCardsByNameReturns(result1 []model.NameMatch, result2 error) {
	fake.findCardsByNameMutex.Lock()
	defer fake.findCardsByNameMutex.Unlock()
	fake.FindCardsByNameStub = nil
	fake.findCardsByNameReturns = struct {
		result1 []model.NameMatch
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) FindCardsByNameReturnsOnCall(i int, result1 []model.NameMatch, result2 error) {
	fake.findCardsByNameMutex.Lock()
	defer fake.findCardsByNameMutex.Unlock()
	fake.FindCardsByNameStub = nil
	if fake.findCardsByNameReturnsOnCall == nil {
		fake.findCardsByNameReturnsOnCall = make(map[int]struct {
			result1 []model.NameMatch
			result2 error
		})
	}
	fake.findCardsByNameReturnsOnCall[i] = struct {
		result1 []model.NameMatch
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) FindPrintingsBySetCode(arg1 context.Context, arg2 string) ([]model.PrintedCard, error) {
	fake.findPrintingsBySetCodeMutex.Lock()
	ret, specificReturn := fake.findPrintingsBySetCodeReturnsOnCall[len(fake.findPrintingsBySetCodeArgsForCall)]
	fake.findPrintingsBySetCodeArgsForCall = append(fake.findPrintingsBySetCodeArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindPrintingsBySetCodeStub
	fakeReturns := fake.findPrintingsBySetCodeReturns
	fake.recordInvocation("FindPrintingsBySetCode", []interface{}{arg1, arg2})
	fake.findPrintingsBySetCodeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) FindPrintingsBySetCodeCallCount() int {
	fake.findPrintingsBySetCodeMutex.RLock()
	defer fake.findPrintingsBySetCodeMutex.RUnlock()
	return len(fake.findPrintingsBySetCodeArgsForCall)
}

func (fake *FakeStore) FindPrintingsBySetCodeCalls(stub func(context.Context, string) ([]model.PrintedCard, error)) {
	fake.findPrintingsBySetCodeMutex.Lock()
	defer fake.findPrintingsBySetCodeMutex.Unlock()
	fake.FindPrintingsBySetCodeStub = stub
}

func (fake *FakeStore) FindPrintingsBySetCodeArgsForCall(i int) (context.Context, string) {
	fake.findPrintingsBySetCodeMutex.RLock()
	defer fake.findPrintingsBySetCodeMutex.RUnlock()
	argsForCall := fake.findPrintingsBySetCodeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) FindPrintingsBySetCodeReturns(result1 []model.PrintedCard, result2 error) {
	fake.findPrintingsBySetCodeMutex.Lock()
	defer fake.findPrintingsBySetCodeMutex.Unlock()
	fake.FindPrintingsBySetCodeStub = nil
	fake.findPrintingsBySetCodeReturns = struct {
		result1 []model.PrintedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) FindPrintingsBySetCodeReturnsOnCall(i int, result1 []model.PrintedCard, result2 error) {
	fake.findPrintingsBySetCodeMutex.Lock()
	defer fake.findPrintingsBySetCodeMutex.Unlock()
	fake.FindPrintingsBySetCodeStub = nil
	if fake.findPrintingsBySetCodeReturnsOnCall == nil {
		fake.findPrintingsBySetCodeReturnsOnCall = make(map[int]struct {
			result1 []model.PrintedCard
			result2 error
		})
	}
	fake.findPrintingsBySetCodeReturnsOnCall[i] = struct {
		result1 []model.PrintedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) FindPrintingsBySetNumber(arg1 context.Context, arg2 string) ([]model.PrintedCard, error) {
	fake.findPrintingsBySetNumberMutex.Lock()
	ret, specificReturn := fake.findPrintingsBySetNumberReturnsOnCall[len(fake.findPrintingsBySetNumberArgsForCall)]
	fake.findPrintingsBySetNumberArgsForCall = append(fake.findPrintingsBySetNumberArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindPrintingsBySetNumberStub
	fakeReturns := fake.findPrintingsBySetNumberReturns
	fake.recordInvocation("FindPrintingsBySetNumber", []interface{}{arg1, arg2})
	fake.findPrintingsBySetNumberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) FindPrintingsBySetNumberCallCount() int {
	fake.findPrintingsBySetNumberMutex.RLock()
	defer fake.findPrintingsBySetNumberMutex.RUnlock()
	return len(fake.findPrintingsBySetNumberArgsForCall)
}

func (fake *FakeStore) FindPrintingsBySetNumberCalls(stub func(context.Context, string) ([]model.PrintedCard, error)) {
	fake.findPrintingsBySetNumberMutex.Lock()
	defer fake.findPrintingsBySetNumberMutex.Unlock()
	fake.FindPrintingsBySetNumberStub = stub
}

func (fake *FakeStore) FindPrintingsBySetNumberArgsForCall(i int) (context.Context, string) {
	fake.findPrintingsBySetNumberMutex.RLock()
	defer fake.findPrintingsBySetNumberMutex.RUnlock()
	argsForCall := fake.findPrintingsBySetNumberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) FindPrintingsBySetNumberReturns(result1 []model.PrintedCard, result2 error) {
	fake.findPrintingsBySetNumberMutex.Lock()
	defer fake.findPrintingsBySetNumberMutex.Unlock()
	fake.FindPrintingsBySetNumberStub = nil
	fake.findPrintingsBySetNumberReturns = struct {
		result1 []model.PrintedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) FindPrintingsBySetNumberReturnsOnCall(i int, result1 []model.PrintedCard, result2 error) {
	fake.findPrintingsBySetNumberMutex.Lock()
	defer fake.findPrintingsBySetNumberMutex.Unlock()
	fake.FindPrintingsBySetNumberStub = nil
	if fake.findPrintingsBySetNumberReturnsOnCall == nil {
		fake.findPrintingsBySetNumberReturnsOnCall = make(map[int]struct {
			result1 []model.PrintedCard
			result2 error
		})
	}
	fake.findPrintingsBySetNumberReturnsOnCall[i] = struct {
		result1 []model.PrintedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) FindPrintingsBySetPrefixAndNumber(arg1 context.Context, arg2 string, arg3 string) ([]model.PrintedCard, error) {
	fake.findPrintingsBySetPrefixAndNumberMutex.Lock()
	ret, specificReturn := fake.findPrintingsBySetPrefixAndNumberReturnsOnCall[len(fake.findPrintingsBySetPrefixAndNumberArgsForCall)]
	fake.findPrintingsBySetPrefixAndNumberArgsForCall = append(fake.findPrintingsBySetPrefixAndNumberArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindPrintingsBySetPrefixAndNumberStub
	fakeReturns := fake.findPrintingsBySetPrefixAndNumberReturns
	fake.recordInvocation("FindPrintingsBySetPrefixAndNumber", []interface{}{arg1, arg2, arg3})
	fake.findPrintingsBySetPrefixAndNumberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) FindPrintingsBySetPrefixAndNumberCallCount() int {
	fake.findPrintingsBySetPrefixAndNumberMutex.RLock()
	defer fake.findPrintingsBySetPrefixAndNumberMutex.RUnlock()
	return len(fake.findPrintingsBySetPrefixAndNumberArgsForCall)
}

func (fake *FakeStore) FindPrintingsBySetPrefixAndNumberCalls(stub func(context.Context, string, string) ([]model.PrintedCard, error)) {
	fake.findPrintingsBySetPrefixAndNumberMutex.Lock()
	defer fake.findPrintingsBySetPrefixAndNumberMutex.Unlock()
	fake.FindPrintingsBySetPrefixAndNumberStub = stub
}

func (fake *FakeStore) FindPrintingsBySetPrefixAndNumberArgsForCall(i int) (context.Context, string, string) {
	fake.findPrintingsBySetPrefixAndNumberMutex.RLock()
	defer fake.findPrintingsBySetPrefixAndNumberMutex.RUnlock()
	argsForCall := fake.findPrintingsBySetPrefixAndNumberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) FindPrintingsBySetPrefixAndNumberReturns(result1 []model.PrintedCard, result2 error) {
	fake.findPrintingsBySetPrefixAndNumberMutex.Lock()
	defer fake.findPrintingsBySetPrefixAndNumberMutex.Unlock()
	fake.FindPrintingsBySetPrefixAndNumberStub = nil
	fake.findPrintingsBySetPrefixAndNumberReturns = struct {
		result1 []model.PrintedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) FindPrintingsBySetPrefixAndNumberReturnsOnCall(i int, result1 []model.PrintedCard, result2 error) {
	fake.findPrintingsBySetPrefixAndNumberMutex.Lock()
	defer fake.findPrintingsBySetPrefixAndNumberMutex.Unlock()
	fake.FindPrintingsBySetPrefixAndNumberStub = nil
	if fake.findPrintingsBySetPrefixAndNumberReturnsOnCall == nil {
		fake.findPrintingsBySetPrefixAndNumberReturnsOnCall = make(map[int]struct {
			result1 []model.PrintedCard
			result2 error
		})
	}
	fake.findPrintingsBySetPrefixAndNumberReturnsOnCall[i] = struct {
		result1 []model.PrintedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SearchCards(arg1 context.Context, arg2 model.CardSearch) ([]model.Card, error) {
	fake.searchCardsMutex.Lock()
	ret, specificReturn := fake.searchCardsReturnsOnCall[len(fake.searchCardsArgsForCall)]
	fake.searchCardsArgsForCall = append(fake.searchCardsArgsForCall, struct {
		arg1 context.Context
		arg2 model.CardSearch
	}{arg1, arg2})
	stub := fake.SearchCardsStub
	fakeReturns := fake.searchCardsReturns
	fake.recordInvocation("SearchCards", []interface{}{arg1, arg2})
	fake.searchCardsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) SearchCardsCallCount() int {
	fake.searchCardsMutex.RLock()
	defer fake.searchCardsMutex.RUnlock()
	return len(fake.searchCardsArgsForCall)
}

func (fake *FakeStore) SearchCardsCalls(stub func(context.Context, model.CardSearch) ([]model.Card, error)) {
	fake.searchCardsMutex.Lock()
	defer fake.searchCardsMutex.Unlock()
	fake.SearchCardsStub = stub
}

func (fake *FakeStore) SearchCardsArgsForCall(i int) (context.Context, model.CardSearch) {
	fake.searchCardsMutex.RLock()
	defer fake.searchCardsMutex.RUnlock()
	argsForCall := fake.searchCardsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) SearchCardsReturns(result1 []model.Card, result2 error) {
	fake.searchCardsMutex.Lock()
	defer fake.searchCardsMutex.Unlock()
	fake.SearchCardsStub = nil
	fake.searchCardsReturns = struct {
		result1 []model.Card
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SearchCardsReturnsOnCall(i int, result1 []model.Card, result2 error) {
	fake.searchCardsMutex.Lock()
	defer fake.searchCardsMutex.Unlock()
	fake.SearchCardsStub = nil
	if fake.searchCardsReturnsOnCall == nil {
		fake.searchCardsReturnsOnCall = make(map[int]struct {
			result1 []model.Card
			result2 error
		})
	}
	fake.searchCardsReturnsOnCall[i] = struct {
		result1 []model.Card
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Store = new(FakeStore)
