// Code generated by counterfeiter. DO NOT EDIT.
package importerfakes

import (
	"context"
	"sync"

	"github.com/simeonkorchev/binder/cmd/cardimport/importer"
	"github.com/simeonkorchev/binder/pkg/ygoprodeck"
)

type FakeFetcher struct {
	FetchAllCardsStub        func(context.Context) ([]ygoprodeck.Card, error)
	fetchAllCardsMutex       sync.RWMutex
	fetchAllCardsArgsForCall []struct {
		arg1 context.Context
	}
	fetchAllCardsReturns struct {
		result1 []ygoprodeck.Card
		result2 error
	}
	fetchAllCardsReturnsOnCall map[int]struct {
		result1 []ygoprodeck.Card
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFetcher) FetchAllCards(arg1 context.Context) ([]ygoprodeck.Card, error) {
	fake.fetchAllCardsMutex.Lock()
	ret, specificReturn := fake.fetchAllCardsReturnsOnCall[len(fake.fetchAllCardsArgsForCall)]
	fake.fetchAllCardsArgsForCall = append(fake.fetchAllCardsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.FetchAllCardsStub
	fakeReturns := fake.fetchAllCardsReturns
	fake.recordInvocation("FetchAllCards", []interface{}{arg1})
	fake.fetchAllCardsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFetcher) FetchAllCardsCallCount() int {
	fake.fetchAllCardsMutex.RLock()
	defer fake.fetchAllCardsMutex.RUnlock()
	return len(fake.fetchAllCardsArgsForCall)
}

func (fake *FakeFetcher) FetchAllCardsCalls(stub func(context.Context) ([]ygoprodeck.Card, error)) {
	fake.fetchAllCardsMutex.Lock()
	defer fake.fetchAllCardsMutex.Unlock()
	fake.FetchAllCardsStub = stub
}

func (fake *FakeFetcher) FetchAllCardsArgsForCall(i int) context.Context {
	fake.fetchAllCardsMutex.RLock()
	defer fake.fetchAllCardsMutex.RUnlock()
	argsForCall := fake.fetchAllCardsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFetcher) FetchAllCardsReturns(result1 []ygoprodeck.Card, result2 error) {
	fake.fetchAllCardsMutex.Lock()
	defer fake.fetchAllCardsMutex.Unlock()
	fake.FetchAllCardsStub = nil
	fake.fetchAllCardsReturns = struct {
		result1 []ygoprodeck.Card
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) FetchAllCardsReturnsOnCall(i int, result1 []ygoprodeck.Card, result2 error) {
	fake.fetchAllCardsMutex.Lock()
	defer fake.fetchAllCardsMutex.Unlock()
	fake.FetchAllCardsStub = nil
	if fake.fetchAllCardsReturnsOnCall == nil {
		fake.fetchAllCardsReturnsOnCall = make(map[int]struct {
			result1 []ygoprodeck.Card
			result2 error
		})
	}
	fake.fetchAllCardsReturnsOnCall[i] = struct {
		result1 []ygoprodeck.Card
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ importer.Fetcher = new(FakeFetcher)
