// Code generated by counterfeiter. DO NOT EDIT.
package importerfakes

import (
	"context"
	"sync"

	"github.com/simeonkorchev/binder/cmd/cardimport/importer"
	"github.com/simeonkorchev/binder/cmd/cardimport/model"
)

type FakeStore struct {
	UpsertBatchStub        func(context.Context, model.Batch) error
	upsertBatchMutex       sync.RWMutex
	upsertBatchArgsForCall []struct {
		arg1 context.Context
		arg2 model.Batch
	}
	upsertBatchReturns struct {
		result1 error
	}
	upsertBatchReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) UpsertBatch(arg1 context.Context, arg2 model.Batch) error {
	fake.upsertBatchMutex.Lock()
	ret, specificReturn := fake.upsertBatchReturnsOnCall[len(fake.upsertBatchArgsForCall)]
	fake.upsertBatchArgsForCall = append(fake.upsertBatchArgsForCall, struct {
		arg1 context.Context
		arg2 model.Batch
	}{arg1, arg2})
	stub := fake.UpsertBatchStub
	fakeReturns := fake.upsertBatchReturns
	fake.recordInvocation("UpsertBatch", []interface{}{arg1, arg2})
	fake.upsertBatchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) UpsertBatchCallCount() int {
	fake.upsertBatchMutex.RLock()
	defer fake.upsertBatchMutex.RUnlock()
	return len(fake.upsertBatchArgsForCall)
}

func (fake *FakeStore) UpsertBatchCalls(stub func(context.Context, model.Batch) error) {
	fake.upsertBatchMutex.Lock()
	defer fake.upsertBatchMutex.Unlock()
	fake.UpsertBatchStub = stub
}

func (fake *FakeStore) UpsertBatchArgsForCall(i int) (context.Context, model.Batch) {
	fake.upsertBatchMutex.RLock()
	defer fake.upsertBatchMutex.RUnlock()
	argsForCall := fake.upsertBatchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) UpsertBatchReturns(result1 error) {
	fake.upsertBatchMutex.Lock()
	defer fake.upsertBatchMutex.Unlock()
	fake.UpsertBatchStub = nil
	fake.upsertBatchReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) UpsertBatchReturnsOnCall(i int, result1 error) {
	fake.upsertBatchMutex.Lock()
	defer fake.upsertBatchMutex.Unlock()
	fake.UpsertBatchStub = nil
	if fake.upsertBatchReturnsOnCall == nil {
		fake.upsertBatchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertBatchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ importer.Store = new(FakeStore)
