// Code generated by counterfeiter. DO NOT EDIT.
package pipelinefakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/cmd/cardimages/model"
	"github.com/simeonkorchev/binder/cmd/cardimages/pipeline"
)

type FakeStore struct {
	CardsNeedingImageStub        func(context.Context, int64, int) ([]model.PendingCard, error)
	cardsNeedingImageMutex       sync.RWMutex
	cardsNeedingImageArgsForCall []struct {
		arg1 context.Context
		arg2 int64
		arg3 int
	}
	cardsNeedingImageReturns struct {
		result1 []model.PendingCard
		result2 error
	}
	cardsNeedingImageReturnsOnCall map[int]struct {
		result1 []model.PendingCard
		result2 error
	}
	SetImageObjectKeyStub        func(context.Context, uuid.UUID, string) error
	setImageObjectKeyMutex       sync.RWMutex
	setImageObjectKeyArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	setImageObjectKeyReturns struct {
		result1 error
	}
	setImageObjectKeyReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) CardsNeedingImage(arg1 context.Context, arg2 int64, arg3 int) ([]model.PendingCard, error) {
	fake.cardsNeedingImageMutex.Lock()
	ret, specificReturn := fake.cardsNeedingImageReturnsOnCall[len(fake.cardsNeedingImageArgsForCall)]
	fake.cardsNeedingImageArgsForCall = append(fake.cardsNeedingImageArgsForCall, struct {
		arg1 context.Context
		arg2 int64
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.CardsNeedingImageStub
	fakeReturns := fake.cardsNeedingImageReturns
	fake.recordInvocation("CardsNeedingImage", []interface{}{arg1, arg2, arg3})
	fake.cardsNeedingImageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) CardsNeedingImageCallCount() int {
	fake.cardsNeedingImageMutex.RLock()
	defer fake.cardsNeedingImageMutex.RUnlock()
	return len(fake.cardsNeedingImageArgsForCall)
}

func (fake *FakeStore) CardsNeedingImageCalls(stub func(context.Context, int64, int) ([]model.PendingCard, error)) {
	fake.cardsNeedingImageMutex.Lock()
	defer fake.cardsNeedingImageMutex.Unlock()
	fake.CardsNeedingImageStub = stub
}

func (fake *FakeStore) CardsNeedingImageArgsForCall(i int) (context.Context, int64, int) {
	fake.cardsNeedingImageMutex.RLock()
	defer fake.cardsNeedingImageMutex.RUnlock()
	argsForCall := fake.cardsNeedingImageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) CardsNeedingImageReturns(result1 []model.PendingCard, result2 error) {
	fake.cardsNeedingImageMutex.Lock()
	defer fake.cardsNeedingImageMutex.Unlock()
	fake.CardsNeedingImageStub = nil
	fake.cardsNeedingImageReturns = struct {
		result1 []model.PendingCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) CardsNeedingImageReturnsOnCall(i int, result1 []model.PendingCard, result2 error) {
	fake.cardsNeedingImageMutex.Lock()
	defer fake.cardsNeedingImageMutex.Unlock()
	fake.CardsNeedingImageStub = nil
	if fake.cardsNeedingImageReturnsOnCall == nil {
		fake.cardsNeedingImageReturnsOnCall = make(map[int]struct {
			result1 []model.PendingCard
			result2 error
		})
	}
	fake.cardsNeedingImageReturnsOnCall[i] = struct {
		result1 []model.PendingCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SetImageObjectKey(arg1 context.Context, arg2 uuid.UUID, arg3 string) error {
	fake.setImageObjectKeyMutex.Lock()
	ret, specificReturn := fake.setImageObjectKeyReturnsOnCall[len(fake.setImageObjectKeyArgsForCall)]
	fake.setImageObjectKeyArgsForCall = append(fake.setImageObjectKeyArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetImageObjectKeyStub
	fakeReturns := fake.setImageObjectKeyReturns
	fake.recordInvocation("SetImageObjectKey", []interface{}{arg1, arg2, arg3})
	fake.setImageObjectKeyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) SetImageObjectKeyCallCount() int {
	fake.setImageObjectKeyMutex.RLock()
	defer fake.setImageObjectKeyMutex.RUnlock()
	return len(fake.setImageObjectKeyArgsForCall)
}

func (fake *FakeStore) SetImageObjectKeyCalls(stub func(context.Context, uuid.UUID, string) error) {
	fake.setImageObjectKeyMutex.Lock()
	defer fake.setImageObjectKeyMutex.Unlock()
	fake.SetImageObjectKeyStub = stub
}

func (fake *FakeStore) SetImageObjectKeyArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.setImageObjectKeyMutex.RLock()
	defer fake.setImageObjectKeyMutex.RUnlock()
	argsForCall := fake.setImageObjectKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) SetImageObjectKeyReturns(result1 error) {
	fake.setImageObjectKeyMutex.Lock()
	defer fake.setImageObjectKeyMutex.Unlock()
	fake.SetImageObjectKeyStub = nil
	fake.setImageObjectKeyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) SetImageObjectKeyReturnsOnCall(i int, result1 error) {
	fake.setImageObjectKeyMutex.Lock()
	defer fake.setImageObjectKeyMutex.Unlock()
	fake.SetImageObjectKeyStub = nil
	if fake.setImageObjectKeyReturnsOnCall == nil {
		fake.setImageObjectKeyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setImageObjectKeyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pipeline.Store = new(FakeStore)
