// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/listing/model"
	"github.com/simeonkorchev/binder/internal/listing/service"
)

type FakeStore struct {
	BrowseListingsStub        func(context.Context, model.ListingSearch) ([]model.ListedCard, error)
	browseListingsMutex       sync.RWMutex
	browseListingsArgsForCall []struct {
		arg1 context.Context
		arg2 model.ListingSearch
	}
	browseListingsReturns struct {
		result1 []model.ListedCard
		result2 error
	}
	browseListingsReturnsOnCall map[int]struct {
		result1 []model.ListedCard
		result2 error
	}
	DeleteListingByIDStub        func(context.Context, uuid.UUID) error
	deleteListingByIDMutex       sync.RWMutex
	deleteListingByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	deleteListingByIDReturns struct {
		result1 error
	}
	deleteListingByIDReturnsOnCall map[int]struct {
		result1 error
	}
	InTxStub        func(context.Context, func(ctx context.Context) error) error
	inTxMutex       sync.RWMutex
	inTxArgsForCall []struct {
		arg1 context.Context
		arg2 func(ctx context.Context) error
	}
	inTxReturns struct {
		result1 error
	}
	inTxReturnsOnCall map[int]struct {
		result1 error
	}
	InsertListingStub        func(context.Context, model.Listing) (model.Listing, error)
	insertListingMutex       sync.RWMutex
	insertListingArgsForCall []struct {
		arg1 context.Context
		arg2 model.Listing
	}
	insertListingReturns struct {
		result1 model.Listing
		result2 error
	}
	insertListingReturnsOnCall map[int]struct {
		result1 model.Listing
		result2 error
	}
	ListingSellerStub        func(context.Context, uuid.UUID) (uuid.UUID, error)
	listingSellerMutex       sync.RWMutex
	listingSellerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	listingSellerReturns struct {
		result1 uuid.UUID
		result2 error
	}
	listingSellerReturnsOnCall map[int]struct {
		result1 uuid.UUID
		result2 error
	}
	SlotSellerStub        func(context.Context, uuid.UUID) (uuid.UUID, error)
	slotSellerMutex       sync.RWMutex
	slotSellerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	slotSellerReturns struct {
		result1 uuid.UUID
		result2 error
	}
	slotSellerReturnsOnCall map[int]struct {
		result1 uuid.UUID
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) BrowseListings(arg1 context.Context, arg2 model.ListingSearch) ([]model.ListedCard, error) {
	fake.browseListingsMutex.Lock()
	ret, specificReturn := fake.browseListingsReturnsOnCall[len(fake.browseListingsArgsForCall)]
	fake.browseListingsArgsForCall = append(fake.browseListingsArgsForCall, struct {
		arg1 context.Context
		arg2 model.ListingSearch
	}{arg1, arg2})
	stub := fake.BrowseListingsStub
	fakeReturns := fake.browseListingsReturns
	fake.recordInvocation("BrowseListings", []interface{}{arg1, arg2})
	fake.browseListingsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) BrowseListingsCallCount() int {
	fake.browseListingsMutex.RLock()
	defer fake.browseListingsMutex.RUnlock()
	return len(fake.browseListingsArgsForCall)
}

func (fake *FakeStore) BrowseListingsCalls(stub func(context.Context, model.ListingSearch) ([]model.ListedCard, error)) {
	fake.browseListingsMutex.Lock()
	defer fake.browseListingsMutex.Unlock()
	fake.BrowseListingsStub = stub
}

func (fake *FakeStore) BrowseListingsArgsForCall(i int) (context.Context, model.ListingSearch) {
	fake.browseListingsMutex.RLock()
	defer fake.browseListingsMutex.RUnlock()
	argsForCall := fake.browseListingsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) BrowseListingsReturns(result1 []model.ListedCard, result2 error) {
	fake.browseListingsMutex.Lock()
	defer fake.browseListingsMutex.Unlock()
	fake.BrowseListingsStub = nil
	fake.browseListingsReturns = struct {
		result1 []model.ListedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) BrowseListingsReturnsOnCall(i int, result1 []model.ListedCard, result2 error) {
	fake.browseListingsMutex.Lock()
	defer fake.browseListingsMutex.Unlock()
	fake.BrowseListingsStub = nil
	if fake.browseListingsReturnsOnCall == nil {
		fake.browseListingsReturnsOnCall = make(map[int]struct {
			result1 []model.ListedCard
			result2 error
		})
	}
	fake.browseListingsReturnsOnCall[i] = struct {
		result1 []model.ListedCard
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) DeleteListingByID(arg1 context.Context, arg2 uuid.UUID) error {
	fake.deleteListingByIDMutex.Lock()
	ret, specificReturn := fake.deleteListingByIDReturnsOnCall[len(fake.deleteListingByIDArgsForCall)]
	fake.deleteListingByIDArgsForCall = append(fake.deleteListingByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.DeleteListingByIDStub
	fakeReturns := fake.deleteListingByIDReturns
	fake.recordInvocation("DeleteListingByID", []interface{}{arg1, arg2})
	fake.deleteListingByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) DeleteListingByIDCallCount() int {
	fake.deleteListingByIDMutex.RLock()
	defer fake.deleteListingByIDMutex.RUnlock()
	return len(fake.deleteListingByIDArgsForCall)
}

func (fake *FakeStore) DeleteListingByIDCalls(stub func(context.Context, uuid.UUID) error) {
	fake.deleteListingByIDMutex.Lock()
	defer fake.deleteListingByIDMutex.Unlock()
	fake.DeleteListingByIDStub = stub
}

func (fake *FakeStore) DeleteListingByIDArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.deleteListingByIDMutex.RLock()
	defer fake.deleteListingByIDMutex.RUnlock()
	argsForCall := fake.deleteListingByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) DeleteListingByIDReturns(result1 error) {
	fake.deleteListingByIDMutex.Lock()
	defer fake.deleteListingByIDMutex.Unlock()
	fake.DeleteListingByIDStub = nil
	fake.deleteListingByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) DeleteListingByIDReturnsOnCall(i int, result1 error) {
	fake.deleteListingByIDMutex.Lock()
	defer fake.deleteListingByIDMutex.Unlock()
	fake.DeleteListingByIDStub = nil
	if fake.deleteListingByIDReturnsOnCall == nil {
		fake.deleteListingByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteListingByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InTx(arg1 context.Context, arg2 func(ctx context.Context) error) error {
	fake.inTxMutex.Lock()
	ret, specificReturn := fake.inTxReturnsOnCall[len(fake.inTxArgsForCall)]
	fake.inTxArgsForCall = append(fake.inTxArgsForCall, struct {
		arg1 context.Context
		arg2 func(ctx context.Context) error
	}{arg1, arg2})
	stub := fake.InTxStub
	fakeReturns := fake.inTxReturns
	fake.recordInvocation("InTx", []interface{}{arg1, arg2})
	fake.inTxMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) InTxCallCount() int {
	fake.inTxMutex.RLock()
	defer fake.inTxMutex.RUnlock()
	return len(fake.inTxArgsForCall)
}

func (fake *FakeStore) InTxCalls(stub func(context.Context, func(ctx context.Context) error) error) {
	fake.inTxMutex.Lock()
	defer fake.inTxMutex.Unlock()
	fake.InTxStub = stub
}

func (fake *FakeStore) InTxArgsForCall(i int) (context.Context, func(ctx context.Context) error) {
	fake.inTxMutex.RLock()
	defer fake.inTxMutex.RUnlock()
	argsForCall := fake.inTxArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) InTxReturns(result1 error) {
	fake.inTxMutex.Lock()
	defer fake.inTxMutex.Unlock()
	fake.InTxStub = nil
	fake.inTxReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InTxReturnsOnCall(i int, result1 error) {
	fake.inTxMutex.Lock()
	defer fake.inTxMutex.Unlock()
	fake.InTxStub = nil
	if fake.inTxReturnsOnCall == nil {
		fake.inTxReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.inTxReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InsertListing(arg1 context.Context, arg2 model.Listing) (model.Listing, error) {
	fake.insertListingMutex.Lock()
	ret, specificReturn := fake.insertListingReturnsOnCall[len(fake.insertListingArgsForCall)]
	fake.insertListingArgsForCall = append(fake.insertListingArgsForCall, struct {
		arg1 context.Context
		arg2 model.Listing
	}{arg1, arg2})
	stub := fake.InsertListingStub
	fakeReturns := fake.insertListingReturns
	fake.recordInvocation("InsertListing", []interface{}{arg1, arg2})
	fake.insertListingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) InsertListingCallCount() int {
	fake.insertListingMutex.RLock()
	defer fake.insertListingMutex.RUnlock()
	return len(fake.insertListingArgsForCall)
}

func (fake *FakeStore) InsertListingCalls(stub func(context.Context, model.Listing) (model.Listing, error)) {
	fake.insertListingMutex.Lock()
	defer fake.insertListingMutex.Unlock()
	fake.InsertListingStub = stub
}

func (fake *FakeStore) InsertListingArgsForCall(i int) (context.Context, model.Listing) {
	fake.insertListingMutex.RLock()
	defer fake.insertListingMutex.RUnlock()
	argsForCall := fake.insertListingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) InsertListingReturns(result1 model.Listing, result2 error) {
	fake.insertListingMutex.Lock()
	defer fake.insertListingMutex.Unlock()
	fake.InsertListingStub = nil
	fake.insertListingReturns = struct {
		result1 model.Listing
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) InsertListingReturnsOnCall(i int, result1 model.Listing, result2 error) {
	fake.insertListingMutex.Lock()
	defer fake.insertListingMutex.Unlock()
	fake.InsertListingStub = nil
	if fake.insertListingReturnsOnCall == nil {
		fake.insertListingReturnsOnCall = make(map[int]struct {
			result1 model.Listing
			result2 error
		})
	}
	fake.insertListingReturnsOnCall[i] = struct {
		result1 model.Listing
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListingSeller(arg1 context.Context, arg2 uuid.UUID) (uuid.UUID, error) {
	fake.listingSellerMutex.Lock()
	ret, specificReturn := fake.listingSellerReturnsOnCall[len(fake.listingSellerArgsForCall)]
	fake.listingSellerArgsForCall = append(fake.listingSellerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.ListingSellerStub
	fakeReturns := fake.listingSellerReturns
	fake.recordInvocation("ListingSeller", []interface{}{arg1, arg2})
	fake.listingSellerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) ListingSellerCallCount() int {
	fake.listingSellerMutex.RLock()
	defer fake.listingSellerMutex.RUnlock()
	return len(fake.listingSellerArgsForCall)
}

func (fake *FakeStore) ListingSellerCalls(stub func(context.Context, uuid.UUID) (uuid.UUID, error)) {
	fake.listingSellerMutex.Lock()
	defer fake.listingSellerMutex.Unlock()
	fake.ListingSellerStub = stub
}

func (fake *FakeStore) ListingSellerArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.listingSellerMutex.RLock()
	defer fake.listingSellerMutex.RUnlock()
	argsForCall := fake.listingSellerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) ListingSellerReturns(result1 uuid.UUID, result2 error) {
	fake.listingSellerMutex.Lock()
	defer fake.listingSellerMutex.Unlock()
	fake.ListingSellerStub = nil
	fake.listingSellerReturns = struct {
		result1 uuid.UUID
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListingSellerReturnsOnCall(i int, result1 uuid.UUID, result2 error) {
	fake.listingSellerMutex.Lock()
	defer fake.listingSellerMutex.Unlock()
	fake.ListingSellerStub = nil
	if fake.listingSellerReturnsOnCall == nil {
		fake.listingSellerReturnsOnCall = make(map[int]struct {
			result1 uuid.UUID
			result2 error
		})
	}
	fake.listingSellerReturnsOnCall[i] = struct {
		result1 uuid.UUID
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SlotSeller(arg1 context.Context, arg2 uuid.UUID) (uuid.UUID, error) {
	fake.slotSellerMutex.Lock()
	ret, specificReturn := fake.slotSellerReturnsOnCall[len(fake.slotSellerArgsForCall)]
	fake.slotSellerArgsForCall = append(fake.slotSellerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.SlotSellerStub
	fakeReturns := fake.slotSellerReturns
	fake.recordInvocation("SlotSeller", []interface{}{arg1, arg2})
	fake.slotSellerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) SlotSellerCallCount() int {
	fake.slotSellerMutex.RLock()
	defer fake.slotSellerMutex.RUnlock()
	return len(fake.slotSellerArgsForCall)
}

func (fake *FakeStore) SlotSellerCalls(stub func(context.Context, uuid.UUID) (uuid.UUID, error)) {
	fake.slotSellerMutex.Lock()
	defer fake.slotSellerMutex.Unlock()
	fake.SlotSellerStub = stub
}

func (fake *FakeStore) SlotSellerArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.slotSellerMutex.RLock()
	defer fake.slotSellerMutex.RUnlock()
	argsForCall := fake.slotSellerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) SlotSellerReturns(result1 uuid.UUID, result2 error) {
	fake.slotSellerMutex.Lock()
	defer fake.slotSellerMutex.Unlock()
	fake.SlotSellerStub = nil
	fake.slotSellerReturns = struct {
		result1 uuid.UUID
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SlotSellerReturnsOnCall(i int, result1 uuid.UUID, result2 error) {
	fake.slotSellerMutex.Lock()
	defer fake.slotSellerMutex.Unlock()
	fake.SlotSellerStub = nil
	if fake.slotSellerReturnsOnCall == nil {
		fake.slotSellerReturnsOnCall = make(map[int]struct {
			result1 uuid.UUID
			result2 error
		})
	}
	fake.slotSellerReturnsOnCall[i] = struct {
		result1 uuid.UUID
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Store = new(FakeStore)
