// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/listing/model"
	"github.com/simeonkorchev/binder/internal/listing/service"
)

type FakeSellerContacts struct {
	ContactForStub        func(context.Context, uuid.UUID) (model.SellerContact, error)
	contactForMutex       sync.RWMutex
	contactForArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	contactForReturns struct {
		result1 model.SellerContact
		result2 error
	}
	contactForReturnsOnCall map[int]struct {
		result1 model.SellerContact
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSellerContacts) ContactFor(arg1 context.Context, arg2 uuid.UUID) (model.SellerContact, error) {
	fake.contactForMutex.Lock()
	ret, specificReturn := fake.contactForReturnsOnCall[len(fake.contactForArgsForCall)]
	fake.contactForArgsForCall = append(fake.contactForArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.ContactForStub
	fakeReturns := fake.contactForReturns
	fake.recordInvocation("ContactFor", []interface{}{arg1, arg2})
	fake.contactForMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSellerContacts) ContactForCallCount() int {
	fake.contactForMutex.RLock()
	defer fake.contactForMutex.RUnlock()
	return len(fake.contactForArgsForCall)
}

func (fake *FakeSellerContacts) ContactForCalls(stub func(context.Context, uuid.UUID) (model.SellerContact, error)) {
	fake.contactForMutex.Lock()
	defer fake.contactForMutex.Unlock()
	fake.ContactForStub = stub
}

func (fake *FakeSellerContacts) ContactForArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.contactForMutex.RLock()
	defer fake.contactForMutex.RUnlock()
	argsForCall := fake.contactForArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSellerContacts) ContactForReturns(result1 model.SellerContact, result2 error) {
	fake.contactForMutex.Lock()
	defer fake.contactForMutex.Unlock()
	fake.ContactForStub = nil
	fake.contactForReturns = struct {
		result1 model.SellerContact
		result2 error
	}{result1, result2}
}

func (fake *FakeSellerContacts) ContactForReturnsOnCall(i int, result1 model.SellerContact, result2 error) {
	fake.contactForMutex.Lock()
	defer fake.contactForMutex.Unlock()
	fake.ContactForStub = nil
	if fake.contactForReturnsOnCall == nil {
		fake.contactForReturnsOnCall = make(map[int]struct {
			result1 model.SellerContact
			result2 error
		})
	}
	fake.contactForReturnsOnCall[i] = struct {
		result1 model.SellerContact
		result2 error
	}{result1, result2}
}

func (fake *FakeSellerContacts) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSellerContacts) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.SellerContacts = new(FakeSellerContacts)
