// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/binder/model"
	"github.com/simeonkorchev/binder/internal/binder/service"
)

type FakeStore struct {
	ClosePositionGapStub        func(context.Context, uuid.UUID, int) error
	closePositionGapMutex       sync.RWMutex
	closePositionGapArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
	}
	closePositionGapReturns struct {
		result1 error
	}
	closePositionGapReturnsOnCall map[int]struct {
		result1 error
	}
	CountSlotsStub        func(context.Context, uuid.UUID) (int, error)
	countSlotsMutex       sync.RWMutex
	countSlotsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	countSlotsReturns struct {
		result1 int
		result2 error
	}
	countSlotsReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	CreateBinderStub        func(context.Context, model.Binder) (model.Binder, error)
	createBinderMutex       sync.RWMutex
	createBinderArgsForCall []struct {
		arg1 context.Context
		arg2 model.Binder
	}
	createBinderReturns struct {
		result1 model.Binder
		result2 error
	}
	createBinderReturnsOnCall map[int]struct {
		result1 model.Binder
		result2 error
	}
	DeleteSlotByIDStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteSlotByIDMutex       sync.RWMutex
	deleteSlotByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteSlotByIDReturns struct {
		result1 error
	}
	deleteSlotByIDReturnsOnCall map[int]struct {
		result1 error
	}
	GetBinderByIDStub        func(context.Context, uuid.UUID) (model.Binder, error)
	getBinderByIDMutex       sync.RWMutex
	getBinderByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	getBinderByIDReturns struct {
		result1 model.Binder
		result2 error
	}
	getBinderByIDReturnsOnCall map[int]struct {
		result1 model.Binder
		result2 error
	}
	GetSlotByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (model.Slot, error)
	getSlotByIDMutex       sync.RWMutex
	getSlotByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getSlotByIDReturns struct {
		result1 model.Slot
		result2 error
	}
	getSlotByIDReturnsOnCall map[int]struct {
		result1 model.Slot
		result2 error
	}
	InTxStub        func(context.Context, func(ctx context.Context) error) error
	inTxMutex       sync.RWMutex
	inTxArgsForCall []struct {
		arg1 context.Context
		arg2 func(ctx context.Context) error
	}
	inTxReturns struct {
		result1 error
	}
	inTxReturnsOnCall map[int]struct {
		result1 error
	}
	InsertSlotStub        func(context.Context, model.Slot) (model.Slot, error)
	insertSlotMutex       sync.RWMutex
	insertSlotArgsForCall []struct {
		arg1 context.Context
		arg2 model.Slot
	}
	insertSlotReturns struct {
		result1 model.Slot
		result2 error
	}
	insertSlotReturnsOnCall map[int]struct {
		result1 model.Slot
		result2 error
	}
	InsertSlotsStub        func(context.Context, []model.Slot) ([]model.Slot, error)
	insertSlotsMutex       sync.RWMutex
	insertSlotsArgsForCall []struct {
		arg1 context.Context
		arg2 []model.Slot
	}
	insertSlotsReturns struct {
		result1 []model.Slot
		result2 error
	}
	insertSlotsReturnsOnCall map[int]struct {
		result1 []model.Slot
		result2 error
	}
	ListBindersByOwnerStub        func(context.Context, uuid.UUID) ([]model.Binder, error)
	listBindersByOwnerMutex       sync.RWMutex
	listBindersByOwnerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	listBindersByOwnerReturns struct {
		result1 []model.Binder
		result2 error
	}
	listBindersByOwnerReturnsOnCall map[int]struct {
		result1 []model.Binder
		result2 error
	}
	ListSlotsInRangeStub        func(context.Context, uuid.UUID, int, int) ([]model.Slot, error)
	listSlotsInRangeMutex       sync.RWMutex
	listSlotsInRangeArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listSlotsInRangeReturns struct {
		result1 []model.Slot
		result2 error
	}
	listSlotsInRangeReturnsOnCall map[int]struct {
		result1 []model.Slot
		result2 error
	}
	MoveSlotPositionStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) error
	moveSlotPositionMutex       sync.RWMutex
	moveSlotPositionArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	moveSlotPositionReturns struct {
		result1 error
	}
	moveSlotPositionReturnsOnCall map[int]struct {
		result1 error
	}
	OpenPositionGapStub        func(context.Context, uuid.UUID, int) error
	openPositionGapMutex       sync.RWMutex
	openPositionGapArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
	}
	openPositionGapReturns struct {
		result1 error
	}
	openPositionGapReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateBinderNameStub        func(context.Context, uuid.UUID, string) (model.Binder, error)
	updateBinderNameMutex       sync.RWMutex
	updateBinderNameArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	updateBinderNameReturns struct {
		result1 model.Binder
		result2 error
	}
	updateBinderNameReturnsOnCall map[int]struct {
		result1 model.Binder
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) ClosePositionGap(arg1 context.Context, arg2 uuid.UUID, arg3 int) error {
	fake.closePositionGapMutex.Lock()
	ret, specificReturn := fake.closePositionGapReturnsOnCall[len(fake.closePositionGapArgsForCall)]
	fake.closePositionGapArgsForCall = append(fake.closePositionGapArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.ClosePositionGapStub
	fakeReturns := fake.closePositionGapReturns
	fake.recordInvocation("ClosePositionGap", []interface{}{arg1, arg2, arg3})
	fake.closePositionGapMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) ClosePositionGapCallCount() int {
	fake.closePositionGapMutex.RLock()
	defer fake.closePositionGapMutex.RUnlock()
	return len(fake.closePositionGapArgsForCall)
}

func (fake *FakeStore) ClosePositionGapCalls(stub func(context.Context, uuid.UUID, int) error) {
	fake.closePositionGapMutex.Lock()
	defer fake.closePositionGapMutex.Unlock()
	fake.ClosePositionGapStub = stub
}

func (fake *FakeStore) ClosePositionGapArgsForCall(i int) (context.Context, uuid.UUID, int) {
	fake.closePositionGapMutex.RLock()
	defer fake.closePositionGapMutex.RUnlock()
	argsForCall := fake.closePositionGapArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) ClosePositionGapReturns(result1 error) {
	fake.closePositionGapMutex.Lock()
	defer fake.closePositionGapMutex.Unlock()
	fake.ClosePositionGapStub = nil
	fake.closePositionGapReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) ClosePositionGapReturnsOnCall(i int, result1 error) {
	fake.closePositionGapMutex.Lock()
	defer fake.closePositionGapMutex.Unlock()
	fake.ClosePositionGapStub = nil
	if fake.closePositionGapReturnsOnCall == nil {
		fake.closePositionGapReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closePositionGapReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) CountSlots(arg1 context.Context, arg2 uuid.UUID) (int, error) {
	fake.countSlotsMutex.Lock()
	ret, specificReturn := fake.countSlotsReturnsOnCall[len(fake.countSlotsArgsForCall)]
	fake.countSlotsArgsForCall = append(fake.countSlotsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.CountSlotsStub
	fakeReturns := fake.countSlotsReturns
	fake.recordInvocation("CountSlots", []interface{}{arg1, arg2})
	fake.countSlotsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) CountSlotsCallCount() int {
	fake.countSlotsMutex.RLock()
	defer fake.countSlotsMutex.RUnlock()
	return len(fake.countSlotsArgsForCall)
}

func (fake *FakeStore) CountSlotsCalls(stub func(context.Context, uuid.UUID) (int, error)) {
	fake.countSlotsMutex.Lock()
	defer fake.countSlotsMutex.Unlock()
	fake.CountSlotsStub = stub
}

func (fake *FakeStore) CountSlotsArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.countSlotsMutex.RLock()
	defer fake.countSlotsMutex.RUnlock()
	argsForCall := fake.countSlotsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) CountSlotsReturns(result1 int, result2 error) {
	fake.countSlotsMutex.Lock()
	defer fake.countSlotsMutex.Unlock()
	fake.CountSlotsStub = nil
	fake.countSlotsReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) CountSlotsReturnsOnCall(i int, result1 int, result2 error) {
	fake.countSlotsMutex.Lock()
	defer fake.countSlotsMutex.Unlock()
	fake.CountSlotsStub = nil
	if fake.countSlotsReturnsOnCall == nil {
		fake.countSlotsReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.countSlotsReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) CreateBinder(arg1 context.Context, arg2 model.Binder) (model.Binder, error) {
	fake.createBinderMutex.Lock()
	ret, specificReturn := fake.createBinderReturnsOnCall[len(fake.createBinderArgsForCall)]
	fake.createBinderArgsForCall = append(fake.createBinderArgsForCall, struct {
		arg1 context.Context
		arg2 model.Binder
	}{arg1, arg2})
	stub := fake.CreateBinderStub
	fakeReturns := fake.createBinderReturns
	fake.recordInvocation("CreateBinder", []interface{}{arg1, arg2})
	fake.createBinderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) CreateBinderCallCount() int {
	fake.createBinderMutex.RLock()
	defer fake.createBinderMutex.RUnlock()
	return len(fake.createBinderArgsForCall)
}

func (fake *FakeStore) CreateBinderCalls(stub func(context.Context, model.Binder) (model.Binder, error)) {
	fake.createBinderMutex.Lock()
	defer fake.createBinderMutex.Unlock()
	fake.CreateBinderStub = stub
}

func (fake *FakeStore) CreateBinderArgsForCall(i int) (context.Context, model.Binder) {
	fake.createBinderMutex.RLock()
	defer fake.createBinderMutex.RUnlock()
	argsForCall := fake.createBinderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) CreateBinderReturns(result1 model.Binder, result2 error) {
	fake.createBinderMutex.Lock()
	defer fake.createBinderMutex.Unlock()
	fake.CreateBinderStub = nil
	fake.createBinderReturns = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) CreateBinderReturnsOnCall(i int, result1 model.Binder, result2 error) {
	fake.createBinderMutex.Lock()
	defer fake.createBinderMutex.Unlock()
	fake.CreateBinderStub = nil
	if fake.createBinderReturnsOnCall == nil {
		fake.createBinderReturnsOnCall = make(map[int]struct {
			result1 model.Binder
			result2 error
		})
	}
	fake.createBinderReturnsOnCall[i] = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) DeleteSlotByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteSlotByIDMutex.Lock()
	ret, specificReturn := fake.deleteSlotByIDReturnsOnCall[len(fake.deleteSlotByIDArgsForCall)]
	fake.deleteSlotByIDArgsForCall = append(fake.deleteSlotByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteSlotByIDStub
	fakeReturns := fake.deleteSlotByIDReturns
	fake.recordInvocation("DeleteSlotByID", []interface{}{arg1, arg2, arg3})
	fake.deleteSlotByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) DeleteSlotByIDCallCount() int {
	fake.deleteSlotByIDMutex.RLock()
	defer fake.deleteSlotByIDMutex.RUnlock()
	return len(fake.deleteSlotByIDArgsForCall)
}

func (fake *FakeStore) DeleteSlotByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteSlotByIDMutex.Lock()
	defer fake.deleteSlotByIDMutex.Unlock()
	fake.DeleteSlotByIDStub = stub
}

func (fake *FakeStore) DeleteSlotByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteSlotByIDMutex.RLock()
	defer fake.deleteSlotByIDMutex.RUnlock()
	argsForCall := fake.deleteSlotByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) DeleteSlotByIDReturns(result1 error) {
	fake.deleteSlotByIDMutex.Lock()
	defer fake.deleteSlotByIDMutex.Unlock()
	fake.DeleteSlotByIDStub = nil
	fake.deleteSlotByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) DeleteSlotByIDReturnsOnCall(i int, result1 error) {
	fake.deleteSlotByIDMutex.Lock()
	defer fake.deleteSlotByIDMutex.Unlock()
	fake.DeleteSlotByIDStub = nil
	if fake.deleteSlotByIDReturnsOnCall == nil {
		fake.deleteSlotByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteSlotByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) GetBinderByID(arg1 context.Context, arg2 uuid.UUID) (model.Binder, error) {
	fake.getBinderByIDMutex.Lock()
	ret, specificReturn := fake.getBinderByIDReturnsOnCall[len(fake.getBinderByIDArgsForCall)]
	fake.getBinderByIDArgsForCall = append(fake.getBinderByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.GetBinderByIDStub
	fakeReturns := fake.getBinderByIDReturns
	fake.recordInvocation("GetBinderByID", []interface{}{arg1, arg2})
	fake.getBinderByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetBinderByIDCallCount() int {
	fake.getBinderByIDMutex.RLock()
	defer fake.getBinderByIDMutex.RUnlock()
	return len(fake.getBinderByIDArgsForCall)
}

func (fake *FakeStore) GetBinderByIDCalls(stub func(context.Context, uuid.UUID) (model.Binder, error)) {
	fake.getBinderByIDMutex.Lock()
	defer fake.getBinderByIDMutex.Unlock()
	fake.GetBinderByIDStub = stub
}

func (fake *FakeStore) GetBinderByIDArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.getBinderByIDMutex.RLock()
	defer fake.getBinderByIDMutex.RUnlock()
	argsForCall := fake.getBinderByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) GetBinderByIDReturns(result1 model.Binder, result2 error) {
	fake.getBinderByIDMutex.Lock()
	defer fake.getBinderByIDMutex.Unlock()
	fake.GetBinderByIDStub = nil
	fake.getBinderByIDReturns = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetBinderByIDReturnsOnCall(i int, result1 model.Binder, result2 error) {
	fake.getBinderByIDMutex.Lock()
	defer fake.getBinderByIDMutex.Unlock()
	fake.GetBinderByIDStub = nil
	if fake.getBinderByIDReturnsOnCall == nil {
		fake.getBinderByIDReturnsOnCall = make(map[int]struct {
			result1 model.Binder
			result2 error
		})
	}
	fake.getBinderByIDReturnsOnCall[i] = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetSlotByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (model.Slot, error) {
	fake.getSlotByIDMutex.Lock()
	ret, specificReturn := fake.getSlotByIDReturnsOnCall[len(fake.getSlotByIDArgsForCall)]
	fake.getSlotByIDArgsForCall = append(fake.getSlotByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetSlotByIDStub
	fakeReturns := fake.getSlotByIDReturns
	fake.recordInvocation("GetSlotByID", []interface{}{arg1, arg2, arg3})
	fake.getSlotByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetSlotByIDCallCount() int {
	fake.getSlotByIDMutex.RLock()
	defer fake.getSlotByIDMutex.RUnlock()
	return len(fake.getSlotByIDArgsForCall)
}

func (fake *FakeStore) GetSlotByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (model.Slot, error)) {
	fake.getSlotByIDMutex.Lock()
	defer fake.getSlotByIDMutex.Unlock()
	fake.GetSlotByIDStub = stub
}

func (fake *FakeStore) GetSlotByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getSlotByIDMutex.RLock()
	defer fake.getSlotByIDMutex.RUnlock()
	argsForCall := fake.getSlotByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) GetSlotByIDReturns(result1 model.Slot, result2 error) {
	fake.getSlotByIDMutex.Lock()
	defer fake.getSlotByIDMutex.Unlock()
	fake.GetSlotByIDStub = nil
	fake.getSlotByIDReturns = struct {
		result1 model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetSlotByIDReturnsOnCall(i int, result1 model.Slot, result2 error) {
	fake.getSlotByIDMutex.Lock()
	defer fake.getSlotByIDMutex.Unlock()
	fake.GetSlotByIDStub = nil
	if fake.getSlotByIDReturnsOnCall == nil {
		fake.getSlotByIDReturnsOnCall = make(map[int]struct {
			result1 model.Slot
			result2 error
		})
	}
	fake.getSlotByIDReturnsOnCall[i] = struct {
		result1 model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) InTx(arg1 context.Context, arg2 func(ctx context.Context) error) error {
	fake.inTxMutex.Lock()
	ret, specificReturn := fake.inTxReturnsOnCall[len(fake.inTxArgsForCall)]
	fake.inTxArgsForCall = append(fake.inTxArgsForCall, struct {
		arg1 context.Context
		arg2 func(ctx context.Context) error
	}{arg1, arg2})
	stub := fake.InTxStub
	fakeReturns := fake.inTxReturns
	fake.recordInvocation("InTx", []interface{}{arg1, arg2})
	fake.inTxMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) InTxCallCount() int {
	fake.inTxMutex.RLock()
	defer fake.inTxMutex.RUnlock()
	return len(fake.inTxArgsForCall)
}

func (fake *FakeStore) InTxCalls(stub func(context.Context, func(ctx context.Context) error) error) {
	fake.inTxMutex.Lock()
	defer fake.inTxMutex.Unlock()
	fake.InTxStub = stub
}

func (fake *FakeStore) InTxArgsForCall(i int) (context.Context, func(ctx context.Context) error) {
	fake.inTxMutex.RLock()
	defer fake.inTxMutex.RUnlock()
	argsForCall := fake.inTxArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) InTxReturns(result1 error) {
	fake.inTxMutex.Lock()
	defer fake.inTxMutex.Unlock()
	fake.InTxStub = nil
	fake.inTxReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InTxReturnsOnCall(i int, result1 error) {
	fake.inTxMutex.Lock()
	defer fake.inTxMutex.Unlock()
	fake.InTxStub = nil
	if fake.inTxReturnsOnCall == nil {
		fake.inTxReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.inTxReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InsertSlot(arg1 context.Context, arg2 model.Slot) (model.Slot, error) {
	fake.insertSlotMutex.Lock()
	ret, specificReturn := fake.insertSlotReturnsOnCall[len(fake.insertSlotArgsForCall)]
	fake.insertSlotArgsForCall = append(fake.insertSlotArgsForCall, struct {
		arg1 context.Context
		arg2 model.Slot
	}{arg1, arg2})
	stub := fake.InsertSlotStub
	fakeReturns := fake.insertSlotReturns
	fake.recordInvocation("InsertSlot", []interface{}{arg1, arg2})
	fake.insertSlotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) InsertSlotCallCount() int {
	fake.insertSlotMutex.RLock()
	defer fake.insertSlotMutex.RUnlock()
	return len(fake.insertSlotArgsForCall)
}

func (fake *FakeStore) InsertSlotCalls(stub func(context.Context, model.Slot) (model.Slot, error)) {
	fake.insertSlotMutex.Lock()
	defer fake.insertSlotMutex.Unlock()
	fake.InsertSlotStub = stub
}

func (fake *FakeStore) InsertSlotArgsForCall(i int) (context.Context, model.Slot) {
	fake.insertSlotMutex.RLock()
	defer fake.insertSlotMutex.RUnlock()
	argsForCall := fake.insertSlotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) InsertSlotReturns(result1 model.Slot, result2 error) {
	fake.insertSlotMutex.Lock()
	defer fake.insertSlotMutex.Unlock()
	fake.InsertSlotStub = nil
	fake.insertSlotReturns = struct {
		result1 model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) InsertSlotReturnsOnCall(i int, result1 model.Slot, result2 error) {
	fake.insertSlotMutex.Lock()
	defer fake.insertSlotMutex.Unlock()
	fake.InsertSlotStub = nil
	if fake.insertSlotReturnsOnCall == nil {
		fake.insertSlotReturnsOnCall = make(map[int]struct {
			result1 model.Slot
			result2 error
		})
	}
	fake.insertSlotReturnsOnCall[i] = struct {
		result1 model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) InsertSlots(arg1 context.Context, arg2 []model.Slot) ([]model.Slot, error) {
	var arg2Copy []model.Slot
	if arg2 != nil {
		arg2Copy = make([]model.Slot, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.insertSlotsMutex.Lock()
	ret, specificReturn := fake.insertSlotsReturnsOnCall[len(fake.insertSlotsArgsForCall)]
	fake.insertSlotsArgsForCall = append(fake.insertSlotsArgsForCall, struct {
		arg1 context.Context
		arg2 []model.Slot
	}{arg1, arg2Copy})
	stub := fake.InsertSlotsStub
	fakeReturns := fake.insertSlotsReturns
	fake.recordInvocation("InsertSlots", []interface{}{arg1, arg2Copy})
	fake.insertSlotsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) InsertSlotsCallCount() int {
	fake.insertSlotsMutex.RLock()
	defer fake.insertSlotsMutex.RUnlock()
	return len(fake.insertSlotsArgsForCall)
}

func (fake *FakeStore) InsertSlotsCalls(stub func(context.Context, []model.Slot) ([]model.Slot, error)) {
	fake.insertSlotsMutex.Lock()
	defer fake.insertSlotsMutex.Unlock()
	fake.InsertSlotsStub = stub
}

func (fake *FakeStore) InsertSlotsArgsForCall(i int) (context.Context, []model.Slot) {
	fake.insertSlotsMutex.RLock()
	defer fake.insertSlotsMutex.RUnlock()
	argsForCall := fake.insertSlotsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) InsertSlotsReturns(result1 []model.Slot, result2 error) {
	fake.insertSlotsMutex.Lock()
	defer fake.insertSlotsMutex.Unlock()
	fake.InsertSlotsStub = nil
	fake.insertSlotsReturns = struct {
		result1 []model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) InsertSlotsReturnsOnCall(i int, result1 []model.Slot, result2 error) {
	fake.insertSlotsMutex.Lock()
	defer fake.insertSlotsMutex.Unlock()
	fake.InsertSlotsStub = nil
	if fake.insertSlotsReturnsOnCall == nil {
		fake.insertSlotsReturnsOnCall = make(map[int]struct {
			result1 []model.Slot
			result2 error
		})
	}
	fake.insertSlotsReturnsOnCall[i] = struct {
		result1 []model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListBindersByOwner(arg1 context.Context, arg2 uuid.UUID) ([]model.Binder, error) {
	fake.listBindersByOwnerMutex.Lock()
	ret, specificReturn := fake.listBindersByOwnerReturnsOnCall[len(fake.listBindersByOwnerArgsForCall)]
	fake.listBindersByOwnerArgsForCall = append(fake.listBindersByOwnerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.ListBindersByOwnerStub
	fakeReturns := fake.listBindersByOwnerReturns
	fake.recordInvocation("ListBindersByOwner", []interface{}{arg1, arg2})
	fake.listBindersByOwnerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) ListBindersByOwnerCallCount() int {
	fake.listBindersByOwnerMutex.RLock()
	defer fake.listBindersByOwnerMutex.RUnlock()
	return len(fake.listBindersByOwnerArgsForCall)
}

func (fake *FakeStore) ListBindersByOwnerCalls(stub func(context.Context, uuid.UUID) ([]model.Binder, error)) {
	fake.listBindersByOwnerMutex.Lock()
	defer fake.listBindersByOwnerMutex.Unlock()
	fake.ListBindersByOwnerStub = stub
}

func (fake *FakeStore) ListBindersByOwnerArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.listBindersByOwnerMutex.RLock()
	defer fake.listBindersByOwnerMutex.RUnlock()
	argsForCall := fake.listBindersByOwnerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) ListBindersByOwnerReturns(result1 []model.Binder, result2 error) {
	fake.listBindersByOwnerMutex.Lock()
	defer fake.listBindersByOwnerMutex.Unlock()
	fake.ListBindersByOwnerStub = nil
	fake.listBindersByOwnerReturns = struct {
		result1 []model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListBindersByOwnerReturnsOnCall(i int, result1 []model.Binder, result2 error) {
	fake.listBindersByOwnerMutex.Lock()
	defer fake.listBindersByOwnerMutex.Unlock()
	fake.ListBindersByOwnerStub = nil
	if fake.listBindersByOwnerReturnsOnCall == nil {
		fake.listBindersByOwnerReturnsOnCall = make(map[int]struct {
			result1 []model.Binder
			result2 error
		})
	}
	fake.listBindersByOwnerReturnsOnCall[i] = struct {
		result1 []model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListSlotsInRange(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]model.Slot, error) {
	fake.listSlotsInRangeMutex.Lock()
	ret, specificReturn := fake.listSlotsInRangeReturnsOnCall[len(fake.listSlotsInRangeArgsForCall)]
	fake.listSlotsInRangeArgsForCall = append(fake.listSlotsInRangeArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListSlotsInRangeStub
	fakeReturns := fake.listSlotsInRangeReturns
	fake.recordInvocation("ListSlotsInRange", []interface{}{arg1, arg2, arg3, arg4})
	fake.listSlotsInRangeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) ListSlotsInRangeCallCount() int {
	fake.listSlotsInRangeMutex.RLock()
	defer fake.listSlotsInRangeMutex.RUnlock()
	return len(fake.listSlotsInRangeArgsForCall)
}

func (fake *FakeStore) ListSlotsInRangeCalls(stub func(context.Context, uuid.UUID, int, int) ([]model.Slot, error)) {
	fake.listSlotsInRangeMutex.Lock()
	defer fake.listSlotsInRangeMutex.Unlock()
	fake.ListSlotsInRangeStub = stub
}

func (fake *FakeStore) ListSlotsInRangeArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listSlotsInRangeMutex.RLock()
	defer fake.listSlotsInRangeMutex.RUnlock()
	argsForCall := fake.listSlotsInRangeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeStore) ListSlotsInRangeReturns(result1 []model.Slot, result2 error) {
	fake.listSlotsInRangeMutex.Lock()
	defer fake.listSlotsInRangeMutex.Unlock()
	fake.ListSlotsInRangeStub = nil
	fake.listSlotsInRangeReturns = struct {
		result1 []model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListSlotsInRangeReturnsOnCall(i int, result1 []model.Slot, result2 error) {
	fake.listSlotsInRangeMutex.Lock()
	defer fake.listSlotsInRangeMutex.Unlock()
	fake.ListSlotsInRangeStub = nil
	if fake.listSlotsInRangeReturnsOnCall == nil {
		fake.listSlotsInRangeReturnsOnCall = make(map[int]struct {
			result1 []model.Slot
			result2 error
		})
	}
	fake.listSlotsInRangeReturnsOnCall[i] = struct {
		result1 []model.Slot
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) MoveSlotPosition(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) error {
	fake.moveSlotPositionMutex.Lock()
	ret, specificReturn := fake.moveSlotPositionReturnsOnCall[len(fake.moveSlotPositionArgsForCall)]
	fake.moveSlotPositionArgsForCall = append(fake.moveSlotPositionArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.MoveSlotPositionStub
	fakeReturns := fake.moveSlotPositionReturns
	fake.recordInvocation("MoveSlotPosition", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.moveSlotPositionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) MoveSlotPositionCallCount() int {
	fake.moveSlotPositionMutex.RLock()
	defer fake.moveSlotPositionMutex.RUnlock()
	return len(fake.moveSlotPositionArgsForCall)
}

func (fake *FakeStore) MoveSlotPositionCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) error) {
	fake.moveSlotPositionMutex.Lock()
	defer fake.moveSlotPositionMutex.Unlock()
	fake.MoveSlotPositionStub = stub
}

func (fake *FakeStore) MoveSlotPositionArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.moveSlotPositionMutex.RLock()
	defer fake.moveSlotPositionMutex.RUnlock()
	argsForCall := fake.moveSlotPositionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeStore) MoveSlotPositionReturns(result1 error) {
	fake.moveSlotPositionMutex.Lock()
	defer fake.moveSlotPositionMutex.Unlock()
	fake.MoveSlotPositionStub = nil
	fake.moveSlotPositionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) MoveSlotPositionReturnsOnCall(i int, result1 error) {
	fake.moveSlotPositionMutex.Lock()
	defer fake.moveSlotPositionMutex.Unlock()
	fake.MoveSlotPositionStub = nil
	if fake.moveSlotPositionReturnsOnCall == nil {
		fake.moveSlotPositionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveSlotPositionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) OpenPositionGap(arg1 context.Context, arg2 uuid.UUID, arg3 int) error {
	fake.openPositionGapMutex.Lock()
	ret, specificReturn := fake.openPositionGapReturnsOnCall[len(fake.openPositionGapArgsForCall)]
	fake.openPositionGapArgsForCall = append(fake.openPositionGapArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.OpenPositionGapStub
	fakeReturns := fake.openPositionGapReturns
	fake.recordInvocation("OpenPositionGap", []interface{}{arg1, arg2, arg3})
	fake.openPositionGapMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) OpenPositionGapCallCount() int {
	fake.openPositionGapMutex.RLock()
	defer fake.openPositionGapMutex.RUnlock()
	return len(fake.openPositionGapArgsForCall)
}

func (fake *FakeStore) OpenPositionGapCalls(stub func(context.Context, uuid.UUID, int) error) {
	fake.openPositionGapMutex.Lock()
	defer fake.openPositionGapMutex.Unlock()
	fake.OpenPositionGapStub = stub
}

func (fake *FakeStore) OpenPositionGapArgsForCall(i int) (context.Context, uuid.UUID, int) {
	fake.openPositionGapMutex.RLock()
	defer fake.openPositionGapMutex.RUnlock()
	argsForCall := fake.openPositionGapArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) OpenPositionGapReturns(result1 error) {
	fake.openPositionGapMutex.Lock()
	defer fake.openPositionGapMutex.Unlock()
	fake.OpenPositionGapStub = nil
	fake.openPositionGapReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) OpenPositionGapReturnsOnCall(i int, result1 error) {
	fake.openPositionGapMutex.Lock()
	defer fake.openPositionGapMutex.Unlock()
	fake.OpenPositionGapStub = nil
	if fake.openPositionGapReturnsOnCall == nil {
		fake.openPositionGapReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.openPositionGapReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) UpdateBinderName(arg1 context.Context, arg2 uuid.UUID, arg3 string) (model.Binder, error) {
	fake.updateBinderNameMutex.Lock()
	ret, specificReturn := fake.updateBinderNameReturnsOnCall[len(fake.updateBinderNameArgsForCall)]
	fake.updateBinderNameArgsForCall = append(fake.updateBinderNameArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.UpdateBinderNameStub
	fakeReturns := fake.updateBinderNameReturns
	fake.recordInvocation("UpdateBinderName", []interface{}{arg1, arg2, arg3})
	fake.updateBinderNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) UpdateBinderNameCallCount() int {
	fake.updateBinderNameMutex.RLock()
	defer fake.updateBinderNameMutex.RUnlock()
	return len(fake.updateBinderNameArgsForCall)
}

func (fake *FakeStore) UpdateBinderNameCalls(stub func(context.Context, uuid.UUID, string) (model.Binder, error)) {
	fake.updateBinderNameMutex.Lock()
	defer fake.updateBinderNameMutex.Unlock()
	fake.UpdateBinderNameStub = stub
}

func (fake *FakeStore) UpdateBinderNameArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.updateBinderNameMutex.RLock()
	defer fake.updateBinderNameMutex.RUnlock()
	argsForCall := fake.updateBinderNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) UpdateBinderNameReturns(result1 model.Binder, result2 error) {
	fake.updateBinderNameMutex.Lock()
	defer fake.updateBinderNameMutex.Unlock()
	fake.UpdateBinderNameStub = nil
	fake.updateBinderNameReturns = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) UpdateBinderNameReturnsOnCall(i int, result1 model.Binder, result2 error) {
	fake.updateBinderNameMutex.Lock()
	defer fake.updateBinderNameMutex.Unlock()
	fake.UpdateBinderNameStub = nil
	if fake.updateBinderNameReturnsOnCall == nil {
		fake.updateBinderNameReturnsOnCall = make(map[int]struct {
			result1 model.Binder
			result2 error
		})
	}
	fake.updateBinderNameReturnsOnCall[i] = struct {
		result1 model.Binder
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Store = new(FakeStore)
