// Code generated by counterfeiter. DO NOT EDIT.
package apifakes

import (
	"context"
	"sync"

	"github.com/simeonkorchev/binder/internal/card/api"
	"github.com/simeonkorchev/binder/internal/card/model"
)

type FakeService struct {
	ResolveScanStub        func(context.Context, model.ScanInput) (model.MatchResult, error)
	resolveScanMutex       sync.RWMutex
	resolveScanArgsForCall []struct {
		arg1 context.Context
		arg2 model.ScanInput
	}
	resolveScanReturns struct {
		result1 model.MatchResult
		result2 error
	}
	resolveScanReturnsOnCall map[int]struct {
		result1 model.MatchResult
		result2 error
	}
	SearchCardsStub        func(context.Context, model.CardSearch) ([]model.Card, error)
	searchCardsMutex       sync.RWMutex
	searchCardsArgsForCall []struct {
		arg1 context.Context
		arg2 model.CardSearch
	}
	searchCardsReturns struct {
		result1 []model.Card
		result2 error
	}
	searchCardsReturnsOnCall map[int]struct {
		result1 []model.Card
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) ResolveScan(arg1 context.Context, arg2 model.ScanInput) (model.MatchResult, error) {
	fake.resolveScanMutex.Lock()
	ret, specificReturn := fake.resolveScanReturnsOnCall[len(fake.resolveScanArgsForCall)]
	fake.resolveScanArgsForCall = append(fake.resolveScanArgsForCall, struct {
		arg1 context.Context
		arg2 model.ScanInput
	}{arg1, arg2})
	stub := fake.ResolveScanStub
	fakeReturns := fake.resolveScanReturns
	fake.recordInvocation("ResolveScan", []interface{}{arg1, arg2})
	fake.resolveScanMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ResolveScanCallCount() int {
	fake.resolveScanMutex.RLock()
	defer fake.resolveScanMutex.RUnlock()
	return len(fake.resolveScanArgsForCall)
}

func (fake *FakeService) ResolveScanCalls(stub func(context.Context, model.ScanInput) (model.MatchResult, error)) {
	fake.resolveScanMutex.Lock()
	defer fake.resolveScanMutex.Unlock()
	fake.ResolveScanStub = stub
}

func (fake *FakeService) ResolveScanArgsForCall(i int) (context.Context, model.ScanInput) {
	fake.resolveScanMutex.RLock()
	defer fake.resolveScanMutex.RUnlock()
	argsForCall := fake.resolveScanArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ResolveScanReturns(result1 model.MatchResult, result2 error) {
	fake.resolveScanMutex.Lock()
	defer fake.resolveScanMutex.Unlock()
	fake.ResolveScanStub = nil
	fake.resolveScanReturns = struct {
		result1 model.MatchResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ResolveScanReturnsOnCall(i int, result1 model.MatchResult, result2 error) {
	fake.resolveScanMutex.Lock()
	defer fake.resolveScanMutex.Unlock()
	fake.ResolveScanStub = nil
	if fake.resolveScanReturnsOnCall == nil {
		fake.resolveScanReturnsOnCall = make(map[int]struct {
			result1 model.MatchResult
			result2 error
		})
	}
	fake.resolveScanReturnsOnCall[i] = struct {
		result1 model.MatchResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchCards(arg1 context.Context, arg2 model.CardSearch) ([]model.Card, error) {
	fake.searchCardsMutex.Lock()
	ret, specificReturn := fake.searchCardsReturnsOnCall[len(fake.searchCardsArgsForCall)]
	fake.searchCardsArgsForCall = append(fake.searchCardsArgsForCall, struct {
		arg1 context.Context
		arg2 model.CardSearch
	}{arg1, arg2})
	stub := fake.SearchCardsStub
	fakeReturns := fake.searchCardsReturns
	fake.recordInvocation("SearchCards", []interface{}{arg1, arg2})
	fake.searchCardsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SearchCardsCallCount() int {
	fake.searchCardsMutex.RLock()
	defer fake.searchCardsMutex.RUnlock()
	return len(fake.searchCardsArgsForCall)
}

func (fake *FakeService) SearchCardsCalls(stub func(context.Context, model.CardSearch) ([]model.Card, error)) {
	fake.searchCardsMutex.Lock()
	defer fake.searchCardsMutex.Unlock()
	fake.SearchCardsStub = stub
}

func (fake *FakeService) SearchCardsArgsForCall(i int) (context.Context, model.CardSearch) {
	fake.searchCardsMutex.RLock()
	defer fake.searchCardsMutex.RUnlock()
	argsForCall := fake.searchCardsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) SearchCardsReturns(result1 []model.Card, result2 error) {
	fake.searchCardsMutex.Lock()
	defer fake.searchCardsMutex.Unlock()
	fake.SearchCardsStub = nil
	fake.searchCardsReturns = struct {
		result1 []model.Card
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchCardsReturnsOnCall(i int, result1 []model.Card, result2 error) {
	fake.searchCardsMutex.Lock()
	defer fake.searchCardsMutex.Unlock()
	fake.SearchCardsStub = nil
	if fake.searchCardsReturnsOnCall == nil {
		fake.searchCardsReturnsOnCall = make(map[int]struct {
			result1 []model.Card
			result2 error
		})
	}
	fake.searchCardsReturnsOnCall[i] = struct {
		result1 []model.Card
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.Service = new(FakeService)
