// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/user/service"
	"github.com/simeonkorchev/binder/internal/user/session"
)

type FakeSessionIssuer struct {
	IssueStub        func(uuid.UUID) (session.Token, error)
	issueMutex       sync.RWMutex
	issueArgsForCall []struct {
		arg1 uuid.UUID
	}
	issueReturns struct {
		result1 session.Token
		result2 error
	}
	issueReturnsOnCall map[int]struct {
		result1 session.Token
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSessionIssuer) Issue(arg1 uuid.UUID) (session.Token, error) {
	fake.issueMutex.Lock()
	ret, specificReturn := fake.issueReturnsOnCall[len(fake.issueArgsForCall)]
	fake.issueArgsForCall = append(fake.issueArgsForCall, struct {
		arg1 uuid.UUID
	}{arg1})
	stub := fake.IssueStub
	fakeReturns := fake.issueReturns
	fake.recordInvocation("Issue", []interface{}{arg1})
	fake.issueMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionIssuer) IssueCallCount() int {
	fake.issueMutex.RLock()
	defer fake.issueMutex.RUnlock()
	return len(fake.issueArgsForCall)
}

func (fake *FakeSessionIssuer) IssueCalls(stub func(uuid.UUID) (session.Token, error)) {
	fake.issueMutex.Lock()
	defer fake.issueMutex.Unlock()
	fake.IssueStub = stub
}

func (fake *FakeSessionIssuer) IssueArgsForCall(i int) uuid.UUID {
	fake.issueMutex.RLock()
	defer fake.issueMutex.RUnlock()
	argsForCall := fake.issueArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSessionIssuer) IssueReturns(result1 session.Token, result2 error) {
	fake.issueMutex.Lock()
	defer fake.issueMutex.Unlock()
	fake.IssueStub = nil
	fake.issueReturns = struct {
		result1 session.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionIssuer) IssueReturnsOnCall(i int, result1 session.Token, result2 error) {
	fake.issueMutex.Lock()
	defer fake.issueMutex.Unlock()
	fake.IssueStub = nil
	if fake.issueReturnsOnCall == nil {
		fake.issueReturnsOnCall = make(map[int]struct {
			result1 session.Token
			result2 error
		})
	}
	fake.issueReturnsOnCall[i] = struct {
		result1 session.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionIssuer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSessionIssuer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.SessionIssuer = new(FakeSessionIssuer)
