// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/simeonkorchev/binder/internal/user/model"
	"github.com/simeonkorchev/binder/internal/user/service"
)

type FakeStore struct {
	EnsureUserByIdentityStub        func(context.Context, uuid.UUID, model.Identity) (model.User, error)
	ensureUserByIdentityMutex       sync.RWMutex
	ensureUserByIdentityArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 model.Identity
	}
	ensureUserByIdentityReturns struct {
		result1 model.User
		result2 error
	}
	ensureUserByIdentityReturnsOnCall map[int]struct {
		result1 model.User
		result2 error
	}
	GetUserByIDStub        func(context.Context, uuid.UUID) (model.User, error)
	getUserByIDMutex       sync.RWMutex
	getUserByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	getUserByIDReturns struct {
		result1 model.User
		result2 error
	}
	getUserByIDReturnsOnCall map[int]struct {
		result1 model.User
		result2 error
	}
	SetUserContactStub        func(context.Context, uuid.UUID, model.Contact) (model.User, error)
	setUserContactMutex       sync.RWMutex
	setUserContactArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 model.Contact
	}
	setUserContactReturns struct {
		result1 model.User
		result2 error
	}
	setUserContactReturnsOnCall map[int]struct {
		result1 model.User
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) EnsureUserByIdentity(arg1 context.Context, arg2 uuid.UUID, arg3 model.Identity) (model.User, error) {
	fake.ensureUserByIdentityMutex.Lock()
	ret, specificReturn := fake.ensureUserByIdentityReturnsOnCall[len(fake.ensureUserByIdentityArgsForCall)]
	fake.ensureUserByIdentityArgsForCall = append(fake.ensureUserByIdentityArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 model.Identity
	}{arg1, arg2, arg3})
	stub := fake.EnsureUserByIdentityStub
	fakeReturns := fake.ensureUserByIdentityReturns
	fake.recordInvocation("EnsureUserByIdentity", []interface{}{arg1, arg2, arg3})
	fake.ensureUserByIdentityMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) EnsureUserByIdentityCallCount() int {
	fake.ensureUserByIdentityMutex.RLock()
	defer fake.ensureUserByIdentityMutex.RUnlock()
	return len(fake.ensureUserByIdentityArgsForCall)
}

func (fake *FakeStore) EnsureUserByIdentityCalls(stub func(context.Context, uuid.UUID, model.Identity) (model.User, error)) {
	fake.ensureUserByIdentityMutex.Lock()
	defer fake.ensureUserByIdentityMutex.Unlock()
	fake.EnsureUserByIdentityStub = stub
}

func (fake *FakeStore) EnsureUserByIdentityArgsForCall(i int) (context.Context, uuid.UUID, model.Identity) {
	fake.ensureUserByIdentityMutex.RLock()
	defer fake.ensureUserByIdentityMutex.RUnlock()
	argsForCall := fake.ensureUserByIdentityArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) EnsureUserByIdentityReturns(result1 model.User, result2 error) {
	fake.ensureUserByIdentityMutex.Lock()
	defer fake.ensureUserByIdentityMutex.Unlock()
	fake.EnsureUserByIdentityStub = nil
	fake.ensureUserByIdentityReturns = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) EnsureUserByIdentityReturnsOnCall(i int, result1 model.User, result2 error) {
	fake.ensureUserByIdentityMutex.Lock()
	defer fake.ensureUserByIdentityMutex.Unlock()
	fake.EnsureUserByIdentityStub = nil
	if fake.ensureUserByIdentityReturnsOnCall == nil {
		fake.ensureUserByIdentityReturnsOnCall = make(map[int]struct {
			result1 model.User
			result2 error
		})
	}
	fake.ensureUserByIdentityReturnsOnCall[i] = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetUserByID(arg1 context.Context, arg2 uuid.UUID) (model.User, error) {
	fake.getUserByIDMutex.Lock()
	ret, specificReturn := fake.getUserByIDReturnsOnCall[len(fake.getUserByIDArgsForCall)]
	fake.getUserByIDArgsForCall = append(fake.getUserByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.GetUserByIDStub
	fakeReturns := fake.getUserByIDReturns
	fake.recordInvocation("GetUserByID", []interface{}{arg1, arg2})
	fake.getUserByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetUserByIDCallCount() int {
	fake.getUserByIDMutex.RLock()
	defer fake.getUserByIDMutex.RUnlock()
	return len(fake.getUserByIDArgsForCall)
}

func (fake *FakeStore) GetUserByIDCalls(stub func(context.Context, uuid.UUID) (model.User, error)) {
	fake.getUserByIDMutex.Lock()
	defer fake.getUserByIDMutex.Unlock()
	fake.GetUserByIDStub = stub
}

func (fake *FakeStore) GetUserByIDArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.getUserByIDMutex.RLock()
	defer fake.getUserByIDMutex.RUnlock()
	argsForCall := fake.getUserByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) GetUserByIDReturns(result1 model.User, result2 error) {
	fake.getUserByIDMutex.Lock()
	defer fake.getUserByIDMutex.Unlock()
	fake.GetUserByIDStub = nil
	fake.getUserByIDReturns = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetUserByIDReturnsOnCall(i int, result1 model.User, result2 error) {
	fake.getUserByIDMutex.Lock()
	defer fake.getUserByIDMutex.Unlock()
	fake.GetUserByIDStub = nil
	if fake.getUserByIDReturnsOnCall == nil {
		fake.getUserByIDReturnsOnCall = make(map[int]struct {
			result1 model.User
			result2 error
		})
	}
	fake.getUserByIDReturnsOnCall[i] = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SetUserContact(arg1 context.Context, arg2 uuid.UUID, arg3 model.Contact) (model.User, error) {
	fake.setUserContactMutex.Lock()
	ret, specificReturn := fake.setUserContactReturnsOnCall[len(fake.setUserContactArgsForCall)]
	fake.setUserContactArgsForCall = append(fake.setUserContactArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 model.Contact
	}{arg1, arg2, arg3})
	stub := fake.SetUserContactStub
	fakeReturns := fake.setUserContactReturns
	fake.recordInvocation("SetUserContact", []interface{}{arg1, arg2, arg3})
	fake.setUserContactMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) SetUserContactCallCount() int {
	fake.setUserContactMutex.RLock()
	defer fake.setUserContactMutex.RUnlock()
	return len(fake.setUserContactArgsForCall)
}

func (fake *FakeStore) SetUserContactCalls(stub func(context.Context, uuid.UUID, model.Contact) (model.User, error)) {
	fake.setUserContactMutex.Lock()
	defer fake.setUserContactMutex.Unlock()
	fake.SetUserContactStub = stub
}

func (fake *FakeStore) SetUserContactArgsForCall(i int) (context.Context, uuid.UUID, model.Contact) {
	fake.setUserContactMutex.RLock()
	defer fake.setUserContactMutex.RUnlock()
	argsForCall := fake.setUserContactArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) SetUserContactReturns(result1 model.User, result2 error) {
	fake.setUserContactMutex.Lock()
	defer fake.setUserContactMutex.Unlock()
	fake.SetUserContactStub = nil
	fake.setUserContactReturns = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SetUserContactReturnsOnCall(i int, result1 model.User, result2 error) {
	fake.setUserContactMutex.Lock()
	defer fake.setUserContactMutex.Unlock()
	fake.SetUserContactStub = nil
	if fake.setUserContactReturnsOnCall == nil {
		fake.setUserContactReturnsOnCall = make(map[int]struct {
			result1 model.User
			result2 error
		})
	}
	fake.setUserContactReturnsOnCall[i] = struct {
		result1 model.User
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Store = new(FakeStore)
